/**
 * ============================================================
 * POSATRACK – Costanti applicazione
 * ============================================================
 * Dati statici che non cambiano a runtime.
 * Per aggiungere un'attrezzatura al catalogo: aggiungi un oggetto
 * in CATALOG rispettando il formato. Non modificare i campi `id`
 * di voci esistenti (sono usati come chiavi nei dati storici).
 */

import type { ActivityTypeMeta, CatalogItem } from '~/types'

// ──────────────────────────────────────────────────────────────────────────────
// TIPI ATTIVITÀ
// Metadati visuali per ciascun tipo di attività tracciabile.
// Il campo `color` è usato in: barra card, pallini log, marker mappa, grafici.
// ──────────────────────────────────────────────────────────────────────────────
export const ACT: Record<string, ActivityTypeMeta> = {
  trasferimento: { label: 'Trasferimento', color: '#3D8EE0', emoji: '🚐' },
  posa:          { label: 'Posa',          color: '#FF5F00', emoji: '🔧' },
  pausa_pranzo:  { label: 'Pausa pranzo',  color: '#F5B800', emoji: '🍽'  },
  altro:         { label: 'Altro',         color: '#8B5CF6', emoji: '📋' },
} as const

// ──────────────────────────────────────────────────────────────────────────────
// CATALOGO ATTREZZATURE
// Usato per popolare la <select> nel modal "Posa".
// Per aggiungere: inserisci un nuovo oggetto { id, label, code }.
// Per rimuovere: elimina la riga (non influenza i dati storici già salvati).
// ──────────────────────────────────────────────────────────────────────────────
export const CATALOG: CatalogItem[] = [
  { id: 'E001', code: '+POSAD01', label: 'Posa in opera di TAVOLO A BILICO', category: 'AGILITY DOG' }, 
  { id: 'E002', code: '+POSAD02', label: 'Posa in opera di PONTE LUNGO', category: 'AGILITY DOG' }, 
  { id: 'E003', code: '+POSAD03', label: 'Posa in opera di RAMPA', category: 'AGILITY DOG' }, 
  { id: 'E004', code: '+POSAD04', label: 'Posa in opera di SALTO NEL CERCHIO', category: 'AGILITY DOG' }, 
  { id: 'E005', code: '+POSAD05', label: 'Posa in opera di SALTO OSTACOLI', category: 'AGILITY DOG' }, 
  { id: 'E006', code: '+POSAD06', label: 'Posa in opera di SALTO OSTACOLO SINGOLO REGOLABILE', category: 'AGILITY DOG' }, 
  { id: 'E007', code: '+POSAD08', label: 'Posa in opera di LABIRINTO', category: 'AGILITY DOG' }, 
  { id: 'E008', code: '+POSU0300.L.2', label: 'Posa in opera di TUNNEL ORSETTO', category: 'AGILITY DOG' }, 
  { id: 'E009', code: '+POS130', label: 'Posa in opera di NIDO INCLUSIVE', category: 'ALTALENE' }, 
  { id: 'E010', code: '+POSB0200', label: 'Posa in opera di ALTALENA VERTICALE PER GRANDI', category: 'ALTALENE' }, 
  { id: 'E011', code: '+POSB0200.110', label: 'Posa in opera di ALTALENA VERTICALE MISTA', category: 'ALTALENE' }, 
  { id: 'E012', code: '+POSB0202', label: 'Posa in opera di ALTALENA VERTICALE PER PICCOLI', category: 'ALTALENE' }, 
  { id: 'E013', code: '+POSB0300', label: 'Posa in opera di ALTALENA GRANDI', category: 'ALTALENE' }, 
  { id: 'E014', code: '+POSB0300.1_P', label: 'Posa in opera di ALTALENA PRIMITIV CON TRAVE ACCIAIO', category: 'ALTALENE' }, 
  { id: 'E015', code: '+POSB0300.110', label: 'Posa in opera di ALTALENA MISTA', category: 'ALTALENE' }, 
  { id: 'E016', code: '+POSB0300.110.2', label: 'Posa in opera di ALTALENA DOPPIA', category: 'ALTALENE' }, 
  { id: 'E017', code: '+POSB0300.110.2.B0400', label: 'Posa in opera di ALTALENA 4 POSTI MISTA + CESTO', category: 'ALTALENE' }, 
  { id: 'E018', code: '+POSB0300.110_P', label: 'Posa in opera di ALTALENA MISTA PRIMITIV', category: 'ALTALENE' }, 
  { id: 'E019', code: '+POSB0300.6', label: 'Posa in opera di ALTALENA ESAGONALE', category: 'ALTALENE' }, 
  { id: 'E020', code: '+POSB0300.7425', label: 'Posa in opera di ALTALENA CESTINO', category: 'ALTALENE' }, 
  { id: 'E021', code: '+POSB0300.ELTERNKIND', label: 'Posa in opera di ALTALENA MAMMA BIMBO', category: 'ALTALENE' }, 
  { id: 'E022', code: '+POSB0300.PZ028', label: 'Posa in opera di ALTALENA GRANDI INCLUSIVE', category: 'ALTALENE' }, 
  { id: 'E023', code: '+POSB0302', label: 'Posa in opera di ALTALENA PICCOLI', category: 'ALTALENE' }, 
  { id: 'E024', code: '+POSB0302.PZ028', label: 'Posa in opera di ALTALENA PICCOLI INCLUSIVE', category: 'ALTALENE' }, 
  { id: 'E025', code: '+POSB0400', label: 'Posa in opera di ALTALENA NIDO', category: 'ALTALENE' }, 
  { id: 'E026', code: '+POSB0400.2', label: 'Posa in opera di ALTALENA NIDO DOPPIA', category: 'ALTALENE' }, 
  { id: 'E027', code: '+POSB0400.2_P', label: 'Posa in opera di ALTALENA NIDO DOPPIA PRIMITIV', category: 'ALTALENE' }, 
  { id: 'E028', code: '+POSB0400.B0300.110', label: 'Posa in opera di ALTALENA 4 POSTI MISTA 2', category: 'ALTALENE' }, 
  { id: 'E029', code: '+POSB0400.PZ028', label: 'Posa in opera di ALTALENA NIDO + INCLUSIVE', category: 'ALTALENE' }, 
  { id: 'E030', code: '+POSB300.110.PAL05', label: 'Posa in opera di ALTALENA ARIETE', category: 'ALTALENE' }, 
  { id: 'E031', code: '+POSB300.PAL05', label: 'Posa in opera di ALTALENA IN CORDA', category: 'ALTALENE' }, 
  { id: 'E032', code: '+POSBE0300B', label: 'Posa in opera di ALTALENA EASY GRANDI', category: 'ALTALENE' }, 
  { id: 'E033', code: '+POSBE0300B.110', label: 'Posa in opera di ALTALENA MISTA EASY', category: 'ALTALENE' }, 
  { id: 'E034', code: '+POSBE0302B', label: 'Posa in opera di ALTALENA EASY PICCOLI', category: 'ALTALENE' }, 
  { id: 'E035', code: '+POSBPS003_P', label: 'Posa in opera di ALTALENA PENDOLO PRIMITIV', category: 'ALTALENE' }, 
  { id: 'E036', code: '+POSBS001', label: 'Posa in opera di AMACA', category: 'ALTALENE' }, 
  { id: 'E037', code: '+POSBS001.B0400_P', label: 'Posa in opera di CESTONE PRIMITIV', category: 'ALTALENE' }, 
  { id: 'E038', code: '+POSBS001.PZ028', label: 'Posa in opera di ALTALENA INCLUSIVE', category: 'ALTALENE' }, 
  { id: 'E039', code: '+POSBS002', label: 'Posa in opera di ALTALENA SINGOLA', category: 'ALTALENE' }, 
  { id: 'E040', code: '+POSBS002.BS001', label: 'Posa in opera di ALTALENA TRIPLA', category: 'ALTALENE' }, 
  { id: 'E041', code: '+POSBS0300_style_INOX', label: 'Posa in opera di ALTALENA PENDOLO INOX', category: 'ALTALENE' }, 
  { id: 'E042', code: '+POS157-3', label: 'Posa in opera di PORTABICICLETTE LIBERTY ORIZZONTALE', category: 'ARREDO URBANO' }, 
  { id: 'E043', code: '+POS208', label: 'Posa in opera di CESTINO TAORMINA', category: 'ARREDO URBANO' }, 
  { id: 'E044', code: '+POS208BIS', label: 'Posa in opera di CESTINO TAORMINA CON COPERCHIO', category: 'ARREDO URBANO' }, 
  { id: 'E045', code: '+POS218', label: 'Posa in opera di CESTONE ELMO', category: 'ARREDO URBANO' }, 
  { id: 'E046', code: '+POS228', label: 'Posa in opera di CESTINO SBARRE', category: 'ARREDO URBANO' }, 
  { id: 'E047', code: '+POS269', label: 'Posa in opera di PENSILINA ECLISSE', category: 'ARREDO URBANO' }, 
  { id: 'E048', code: '+POS286', label: 'Posa in opera di PORTABICICLETTE LIBERTY', category: 'ARREDO URBANO' }, 
  { id: 'E049', code: '+POS298', label: 'Posa in opera di PANCHINA CLEMATIS', category: 'ARREDO URBANO' }, 
  { id: 'E050', code: '+POS318', label: 'Posa in opera di CESTIINO ALADINO', category: 'ARREDO URBANO' }, 
  { id: 'E051', code: '+POS318BIS', label: 'Posa in opera di CESTINO ALADINO CON COPERCHIO', category: 'ARREDO URBANO' }, 
  { id: 'E052', code: '+POS376', label: 'Posa in opera di CESTINO TRIO CON POSACENERE', category: 'ARREDO URBANO' }, 
  { id: 'E053', code: '+POS386', label: 'Posa in opera di PORTABICICLETTE MILANO', category: 'ARREDO URBANO' }, 
  { id: 'E054', code: '+POS414', label: 'Posa in opera di PORTABICICLETTE SPIRO', category: 'ARREDO URBANO' }, 
  { id: 'E055', code: '+POS442', label: 'Posa in opera di CESTINO DIFFERENZIATA', category: 'ARREDO URBANO' }, 
  { id: 'E056', code: '+POS950BIS', label: 'Posa in opera di FIORERIA ORCHIDEA', category: 'ARREDO URBANO' }, 
  { id: 'E057', code: '+POSCL300', label: 'Posa in opera di PENSILINA ATTESA AUTOBUS', category: 'ARREDO URBANO' }, 
  { id: 'E058', code: '+POSGT-06', label: 'Posa in opera di STEP', category: 'ARREDO URBANO' }, 
  { id: 'E059', code: '+POSH0300', label: 'Posa in opera di PANCHINA VICENZA', category: 'ARREDO URBANO' }, 
  { id: 'E060', code: '+POSH0300BIG', label: 'Posa in opera di PANCHINA DEL GIGANTE', category: 'ARREDO URBANO' }, 
  { id: 'E061', code: '+POSH0600', label: 'Posa in opera di PANCHINA GALLIO', category: 'ARREDO URBANO' }, 
  { id: 'E062', code: '+POSH0700', label: 'Posa in opera di PANCHINA TIROLO', category: 'ARREDO URBANO' }, 
  { id: 'E063', code: '+POSH0900', label: 'Posa in opera di PANCHINA AUSTRIA', category: 'ARREDO URBANO' }, 
  { id: 'E064', code: '+POSH1020', label: 'Posa in opera di PANCHINA DOLOMITI', category: 'ARREDO URBANO' }, 
  { id: 'E065', code: '+POSH3001.J02001', label: 'Posa in opera di PANCHINA SPRING LEONE BABY', category: 'ARREDO URBANO' }, 
  { id: 'E066', code: '+POSH5000', label: 'Posa in opera di ANFITEATRO', category: 'ARREDO URBANO' }, 
  { id: 'E067', code: '+POSHL0200', label: 'Posa in opera di PANCHINA LUMÉA', category: 'ARREDO URBANO' }, 
  { id: 'E068', code: '+POSHL0200J', label: 'Posa in opera di PANCHINA LUMÉA A MOLLA', category: 'ARREDO URBANO' }, 
  { id: 'E069', code: '+POSI0100', label: 'Posa in opera di PIC-NIC', category: 'ARREDO URBANO' }, 
  { id: 'E070', code: '+POSI0100H', label: 'Posa in opera di PIC-NIC INCLUSIVE', category: 'ARREDO URBANO' }, 
  { id: 'E071', code: '+POSI0101', label: 'Posa in opera di PIC-NIC BABY', category: 'ARREDO URBANO' }, 
  { id: 'E072', code: '+POSI0200', label: 'Posa in opera di PIC NIC POLY', category: 'ARREDO URBANO' }, 
  { id: 'E073', code: '+POSI0300', label: 'Posa in opera di FIRENZE', category: 'ARREDO URBANO' }, 
  { id: 'E074', code: '+POSI0300H', label: 'Posa in opera di FIRENZE INCLUSIVE', category: 'ARREDO URBANO' }, 
  { id: 'E075', code: '+POSI0301', label: 'Posa in opera di FIRENZE BABY', category: 'ARREDO URBANO' }, 
  { id: 'E076', code: '+POSI0301F1', label: 'Posa in opera di PIC NIC LEONE', category: 'ARREDO URBANO' }, 
  { id: 'E077', code: '+POSI0301H', label: 'Posa in opera di FIRENZE BABY INCLUSIVE', category: 'ARREDO URBANO' }, 
  { id: 'E078', code: '+POSI0650', label: 'Posa in opera di TAVOLO GIROTONDO', category: 'ARREDO URBANO' }, 
  { id: 'E079', code: '+POSI0680', label: 'Posa in opera di TAVOLO MARGHERITA', category: 'ARREDO URBANO' }, 
  { id: 'E080', code: '+POSI0680H', label: 'Posa in opera di TAVOLO MARGHERITA INCLUSIVE', category: 'ARREDO URBANO' }, 
  { id: 'E081', code: '+POSI0700', label: 'Posa in opera di ROANA', category: 'ARREDO URBANO' }, 
  { id: 'E082', code: '+POSI0800', label: 'Posa in opera di OASI PANCA + TAVOLO', category: 'ARREDO URBANO' }, 
  { id: 'E083', code: '+POSIL0200', label: 'Posa in opera di PIC-NIC LUMÉA', category: 'ARREDO URBANO' }, 
  { id: 'E084', code: '+POSIT0300', label: 'Posa in opera di TAVOLO AUSTRIA', category: 'ARREDO URBANO' }, 
  { id: 'E085', code: '+POSIT0400', label: 'Posa in opera di TAVOLO TIROLO', category: 'ARREDO URBANO' }, 
  { id: 'E086', code: '+POSL0100', label: 'Posa in opera di BACHECA LEOGRA', category: 'ARREDO URBANO' }, 
  { id: 'E087', code: '+POSL0101', label: 'Posa in opera di BACHECA STANDARD', category: 'ARREDO URBANO' }, 
  { id: 'E088', code: '+POSL0200', label: 'Posa in opera di BACHECA TRIESTE PICCOLA', category: 'ARREDO URBANO' }, 
  { id: 'E089', code: '+POSL0300', label: 'Posa in opera di BACHECA TRIESTE GRANDE', category: 'ARREDO URBANO' }, 
  { id: 'E090', code: '+POSM0100', label: 'Posa in opera di CESTINO ZINCATO', category: 'ARREDO URBANO' }, 
  { id: 'E091', code: '+POSM0101', label: 'Posa in opera di CESTINO VERNICIATO', category: 'ARREDO URBANO' }, 
  { id: 'E092', code: '+POSM0200', label: 'Posa in opera di CESTINO RIVESTITO', category: 'ARREDO URBANO' }, 
  { id: 'E093', code: '+POSM0300', label: 'Posa in opera di CESTINO LONDON', category: 'ARREDO URBANO' }, 
  { id: 'E094', code: '+POSML0100', label: 'Posa in opera di CESTINO LUMÉA', category: 'ARREDO URBANO' }, 
  { id: 'E095', code: '+POSN260', label: 'Posa in opera di FRECCIA DIREZIONALE FOREX', category: 'ARREDO URBANO' }, 
  { id: 'E096', code: '+POSNO200', label: 'Posa in opera di FRECCIA DIREZIONALE LEGNO', category: 'ARREDO URBANO' }, 
  { id: 'E097', code: '+POSO0100', label: 'Posa in opera di STACCIONATA RUSTICO', category: 'ARREDO URBANO' }, 
  { id: 'E098', code: '+POSO0100/3', label: 'Posa in opera di STACCIONATA RUSTICO 3 CORRENTI', category: 'ARREDO URBANO' }, 
  { id: 'E099', code: '+POSO0300', label: 'Posa in opera di STACCIONATA MILLE', category: 'ARREDO URBANO' }, 
  { id: 'E100', code: '+POSO0400', label: 'Posa in opera di STACCIONATA VICENZA', category: 'ARREDO URBANO' }, 
  { id: 'E101', code: '+POSO0500', label: 'Posa in opera di STACCIONATA DOLOMITI', category: 'ARREDO URBANO' }, 
  { id: 'E102', code: '+POSO0701', label: 'Posa in opera di STACCIONATA IPPICA', category: 'ARREDO URBANO' }, 
  { id: 'E103', code: '+POSO0990', label: 'Posa in opera di STACCIONATA TRIESTE', category: 'ARREDO URBANO' }, 
  { id: 'E104', code: '+POSO1200', label: 'Posa in opera di STACCIONATA ARZIGNANO', category: 'ARREDO URBANO' }, 
  { id: 'E105', code: '+POSO2000/100', label: 'Posa in opera di STACCIONATA BARRIERA FERMA-AUTO', category: 'ARREDO URBANO' }, 
  { id: 'E106', code: '+POSQ0500', label: 'Posa in opera di PORTABICICLETTE ORIZZONTALE LEGNO', category: 'ARREDO URBANO' }, 
  { id: 'E107', code: '+POSQ0600', label: 'Posa in opera di GAZEBO VENEZIA', category: 'ARREDO URBANO' }, 
  { id: 'E108', code: '+POSQ0801', label: 'Posa in opera di GAZEBO MALO', category: 'ARREDO URBANO' }, 
  { id: 'E109', code: '+POSQL0200C', label: 'Posa in opera di GAZEBO LUMÉA CON RICARICA E-BIKE', category: 'ARREDO URBANO' }, 
  { id: 'E110', code: '+POSTAV.10001', label: 'Posa in opera di TAVOLO PING PONG IN CLS', category: 'ARREDO URBANO' }, 
  { id: 'E111', code: '+POSYY0100', label: 'Posa in opera di FONTANELLA', category: 'ARREDO URBANO' }, 
  { id: 'E112', code: '+POSAF102SSU.KK030', label: 'Posa in opera di BABELE H240 CON PALESTRA VOLANTE', category: 'BABELE' }, 
  { id: 'E113', code: '+POSAF102SSU.SW24', label: 'Posa in opera di BABELE H240', category: 'BABELE' }, 
  { id: 'E114', code: '+POSAF102SSU.SWE24.S_L', label: 'Posa in opera di BABELE H240 CON SCIVOLO LEAVES', category: 'BABELE' }, 
  { id: 'E115', code: '+POSAF102SSU.SWE24.S14', label: 'Posa in opera di BABELE H240 +TORRI', category: 'BABELE' }, 
  { id: 'E116', code: '+POSAF102SSU.SWE24_L', label: 'Posa in opera di BABELE H240 LEAVES', category: 'BABELE' }, 
  { id: 'E117', code: '+POSAF102SSU.SWE24_M', label: 'Posa in opera di BABELE H240 +TORRI', category: 'BABELE' }, 
  { id: 'E118', code: '+POSAF102SSU.SWE34', label: 'Posa in opera di BABELE H340', category: 'BABELE' }, 
  { id: 'E119', code: '+POSAF102SSU.SWE34.S9', label: 'Posa in opera di BABELE H340 CON DUE TORRI', category: 'BABELE' }, 
  { id: 'E120', code: '+POSAF102SSU.SWE34_L', label: 'Posa in opera di BABELE H340 LEAVES', category: 'BABELE' }, 
  { id: 'E121', code: '+POSAF102SSU.SWE34PD6', label: 'Posa in opera di BABELE H240+H340', category: 'BABELE' }, 
  { id: 'E122', code: '+POSAF102SSU.SWE34PD6_L', label: 'Posa in opera di BABELE H240+H340 LEAVES', category: 'BABELE' }, 
  { id: 'E123', code: '+POSAF102SSU.SWE44', label: 'Posa in opera di BABELE H440', category: 'BABELE' }, 
  { id: 'E124', code: '+POSAF102SSU.SWE44.S14', label: 'Posa in opera di BABELE H440 CON TORRI LATERALI', category: 'BABELE' }, 
  { id: 'E125', code: '+POSAF102SSU.SWE44_C', label: 'Posa in opera di BABELE H440 +TORRI LATERALI COLORI', category: 'BABELE' }, 
  { id: 'E126', code: '+POSAF102SSU.SWE44_L', label: 'Posa in opera di BABELE H440', category: 'BABELE' }, 
  { id: 'E127', code: '+POSAF102SSU.SWE44PI6', label: 'Posa in opera di BABELE H340+H440', category: 'BABELE' }, 
  { id: 'E128', code: '+POSAF102SSU.SWE44PI6_L', label: 'Posa in opera di BABELE H340+H440 LEAVES', category: 'BABELE' }, 
  { id: 'E129', code: '+POSE00S5.U0600.T_C', label: 'Posa in opera di CASETTA VENERE CON PANNELLI INTERATTIVI COLORI', category: 'CASETTE' }, 
  { id: 'E130', code: '+POSE0100', label: 'Posa in opera di CASETTA WOOD', category: 'CASETTE' }, 
  { id: 'E131', code: '+POSE0100.ES005', label: 'Posa in opera di VILLAGGIO WOOD', category: 'CASETTE' }, 
  { id: 'E132', code: '+POSE0100.GT-01', label: 'Posa in opera di CASETTA WOOD INCLUSIVE', category: 'CASETTE' }, 
  { id: 'E133', code: '+POSE0100_P', label: 'Posa in opera di CASETTA WOOD PRIMITIV', category: 'CASETTE' }, 
  { id: 'E134', code: '+POSE0200', label: 'Posa in opera di CAPANNA CHEYENNE', category: 'CASETTE' }, 
  { id: 'E135', code: '+POSE0200.GT-07', label: 'Posa in opera di CAPANNA CHEYENNE CON SEDUTE', category: 'CASETTE' }, 
  { id: 'E136', code: '+POSEF001', label: 'Posa in opera di CASETTA MIRTILLO - FANTASY', category: 'CASETTE' }, 
  { id: 'E137', code: '+POSEF001_L', label: 'Posa in opera di CASETTA MIRTILLO - LEAVES', category: 'CASETTE' }, 
  { id: 'E138', code: '+POSEF001-H', label: 'Posa in opera di CASETTA MIRTILLO INCLUSIVE', category: 'CASETTE' }, 
  { id: 'E139', code: '+POSES004', label: 'Posa in opera di CASETTA STELLA', category: 'CASETTE' }, 
  { id: 'E140', code: '+POSES005', label: 'Posa in opera di CASETTA VENERE', category: 'CASETTE' }, 
  { id: 'E141', code: '+POSES005.U0600.T_L', label: 'Posa in opera di CASETTA VENERE CON PANNELLI INTERATTIVI', category: 'CASETTE' }, 
  { id: 'E142', code: '+POSES005.U0600_L', label: 'Posa in opera di CASETTA MIRTILLO MUSICALE', category: 'CASETTE' }, 
  { id: 'E143', code: '+POSES1100.AF100B', label: 'Posa in opera di VILLAGGIO INCLUSIVE', category: 'CASETTE' }, 
  { id: 'E144', code: '+POSES1100.ES005_L', label: 'Posa in opera di VILLAGGIO WOOD', category: 'CASETTE' }, 
  { id: 'E145', code: '+POSES1100.U0300', label: 'Posa in opera di VILLAGGIO LILLY CON TUNNEL', category: 'CASETTE' }, 
  { id: 'E146', code: '+POSES1100_L', label: 'Posa in opera di VILLAGGIO LILLY', category: 'CASETTE' }, 
  { id: 'E147', code: '+POSV0300.BV-4', label: 'Posa in opera di VILLAGGIO SIMBA', category: 'CASETTE' }, 
  { id: 'E148', code: '+POSV0300.BV-4_L', label: 'Posa in opera di VILLAGE INCLUSIVE', category: 'CASETTE' }, 
  { id: 'E149', code: '+POS16080', label: 'Posa in opera di CASTELLO GIGANTE', category: 'COLLABORAZIONI' }, 
  { id: 'E150', code: '+POS16103', label: 'Posa in opera di RIFUGIO DEL BOSCO GRANDE', category: 'COLLABORAZIONI' }, 
  { id: 'E151', code: '+POS16111', label: 'Posa in opera di MAFALDA GRANDE', category: 'COLLABORAZIONI' }, 
  { id: 'E152', code: '+POS20124', label: 'Posa in opera di TRIPLA TORRE', category: 'COLLABORAZIONI' }, 
  { id: 'E153', code: '+POS20153', label: 'Posa in opera di PANORAMICO', category: 'COLLABORAZIONI' }, 
  { id: 'E154', code: '+POS20208', label: 'Posa in opera di PALLONE', category: 'COLLABORAZIONI' }, 
  { id: 'E155', code: '+POS20279', label: 'Posa in opera di TRATTORE CON ARATRO', category: 'COLLABORAZIONI' }, 
  { id: 'E156', code: '+POS25012', label: 'Posa in opera di FARO AZZURRO', category: 'COLLABORAZIONI' }, 
  { id: 'E157', code: '+POS25024', label: 'Posa in opera di FURNARIOS RUFUS', category: 'COLLABORAZIONI' }, 
  { id: 'E158', code: '+POSAF100.PAL-01_C', label: 'Posa in opera di FATA CON PALESTRA - COLORI', category: 'COLORI' }, 
  { id: 'E159', code: '+POSAF100.SW-14.PAL-01_C', label: 'Posa in opera di FATA CON SCIVOLO A TUBO E PALESTRA - COLORI', category: 'COLORI' }, 
  { id: 'E160', code: '+POSAF100.SW-14_C', label: 'Posa in opera di FATA CON SCIVOLO A TUBO - COLORI', category: 'COLORI' }, 
  { id: 'E161', code: '+POSAF100B.PAL-01_C', label: 'Posa in opera di FATA BABY CON PALESTRA - COLORI', category: 'COLORI' }, 
  { id: 'E162', code: '+POSAF100B.SG-14_C', label: 'Posa in opera di FRAGOLA CON PERTICA - COLORI', category: 'COLORI' }, 
  { id: 'E163', code: '+POSAF100B.SVPX-6_C', label: 'Posa in opera di FATA BABY 60 - COLORI', category: 'COLORI' }, 
  { id: 'E164', code: '+POSAF101.EPAL_C', label: 'Posa in opera di HOOK CON PALESTRA - COLORI', category: 'COLORI' }, 
  { id: 'E165', code: '+POSAF101B.ALT-01_C', label: 'Posa in opera di HOOK BABY CON ALTALENA - COLORI', category: 'COLORI' }, 
  { id: 'E166', code: '+POSAF102.EPAL-01_C', label: 'Posa in opera di MERLINO CON PALESTRA - COLORI', category: 'COLORI' }, 
  { id: 'E167', code: '+POSAF102.PAL-10_C', label: 'Posa in opera di HOOK BABY CON PALESTRA - COLORI', category: 'COLORI' }, 
  { id: 'E168', code: '+POSAF102.SG-9_C', label: 'Posa in opera di MERLINO CON SCALA A GRADONI - COLORI', category: 'COLORI' }, 
  { id: 'E169', code: '+POSAF102b.GT-06_C', label: 'Posa in opera di MERLINO BABY CON ARREDO - COLORI', category: 'COLORI' }, 
  { id: 'E170', code: '+POSAF102B.SVPX-9_C', label: 'Posa in opera di MERLINO BABY CON SCIVOLO - COLORI', category: 'COLORI' }, 
  { id: 'E171', code: '+POSAF103.PAL-10_C', label: 'Posa in opera di DRAGON CON PALESTRA A FUNI E SCIVOLO A TUBO - COLORI', category: 'COLORI' }, 
  { id: 'E172', code: '+POSAF103.PD-6_C', label: 'Posa in opera di DRAGON CON PONTE TIBETANO - COLORI', category: 'COLORI' }, 
  { id: 'E173', code: '+POSAF104.PAL-10_C', label: 'Posa in opera di ROMA CON PALESTRA A FUNI - COLORI', category: 'COLORI' }, 
  { id: 'E174', code: '+POSAF104K.SW-19_C', label: 'Posa in opera di RIVIERA - COLORI', category: 'COLORI' }, 
  { id: 'E175', code: '+POSAF203.PAL-02_C', label: 'Posa in opera di CAPRI CON PALESTRA - COLORI', category: 'COLORI' }, 
  { id: 'E176', code: '+POSAF203.SW-14_C', label: 'Posa in opera di CAPRI CON SCIVOLO A TUBO - COLORI', category: 'COLORI' }, 
  { id: 'E177', code: '+POSAF604AP_C', label: 'Posa in opera di ISCHIA CON ALTALENA E PALESTRA - COLORI', category: 'COLORI' }, 
  { id: 'E178', code: '+POSAF604WU_C', label: 'Posa in opera di ISCHIA CON SCIVOLO A TUBO - COLORI', category: 'COLORI' }, 
  { id: 'E179', code: '+POSAF703.SW-14_C', label: 'Posa in opera di ANDROMEDA - COLORI', category: 'COLORI' }, 
  { id: 'E180', code: '+POSF0100', label: 'Posa in opera di DONDOLO A BILICO', category: 'DONDOLI' }, 
  { id: 'E181', code: '+POSF0100.2_P', label: 'Posa in opera di TRAVE A MOLLA PRIMITIV', category: 'DONDOLI' }, 
  { id: 'E182', code: '+POSF0100.3', label: 'Posa in opera di DONDOLO CURVO', category: 'DONDOLI' }, 
  { id: 'E183', code: '+POSF0100.4', label: 'Posa in opera di MEZZALUNA', category: 'DONDOLI' }, 
  { id: 'E184', code: '+POSF0100.J07001', label: 'Posa in opera di DONDOLO TRIPLO BALENA', category: 'DONDOLI' }, 
  { id: 'E185', code: '+POSF0100_P', label: 'Posa in opera di DONDOLO PRIMITIV', category: 'DONDOLI' }, 
  { id: 'E186', code: '+POSF0101', label: 'Posa in opera di DONDOLO A BILICO 4 POSTI', category: 'DONDOLI' }, 
  { id: 'E187', code: '+POSF0800', label: 'Posa in opera di DONDOLO WOOD', category: 'DONDOLI' }, 
  { id: 'E188', code: '+POSF0800.4', label: 'Posa in opera di DONDOLO WOOD 4 POSTI', category: 'DONDOLI' }, 
  { id: 'E189', code: '+POSF0800H', label: 'Posa in opera di DONDOLO INLUSIVE', category: 'DONDOLI' }, 
  { id: 'E190', code: '+POSF0800H.2_P', label: 'Posa in opera di ZATTERA A MOLLA PRIMITIV', category: 'DONDOLI' }, 
  { id: 'E191', code: '+POSAE100', label: 'Posa in opera di ALBICOCCA  - EASY', category: 'EASY' }, 
  { id: 'E192', code: '+POSAE100.EQ-14', label: 'Posa in opera di ALBICOCCA SENZA TETTO - EASY', category: 'EASY' }, 
  { id: 'E193', code: '+POSAE100.S-14', label: 'Posa in opera di ALBICOCCA CON SCALA - EASY', category: 'EASY' }, 
  { id: 'E194', code: '+POSAE100.S4-14', label: 'Posa in opera di PESCA BABY CON SCALA A PIOLI - EASY', category: 'EASY' }, 
  { id: 'E195', code: '+POSAE100A', label: 'Posa in opera di ALBICOCCA CON ALTALENA - EASY', category: 'EASY' }, 
  { id: 'E196', code: '+POSAE100A.EPAL', label: 'Posa in opera di ALBICOCCA CON ALTALENA E PALESTRA - EASY', category: 'EASY' }, 
  { id: 'E197', code: '+POSAE100AB', label: 'Posa in opera di ALBICOCCA BABY CON ALTALENA - EASY', category: 'EASY' }, 
  { id: 'E198', code: '+POSAE100B', label: 'Posa in opera di ALBICOCCA BABY - EASY', category: 'EASY' }, 
  { id: 'E199', code: '+POSAE100B.EQ-9', label: 'Posa in opera di ALBICOCCA BABY SENZA TETTO - EASY', category: 'EASY' }, 
  { id: 'E200', code: '+POSAE100B.S4-9', label: 'Posa in opera di ALBICOCCA BABY CON SCALA A PIOLI - EASY', category: 'EASY' }, 
  { id: 'E201', code: '+POSAE100B.TT-17', label: 'Posa in opera di CILIEGIA - EASY', category: 'EASY' }, 
  { id: 'E202', code: '+POSAE100P', label: 'Posa in opera di ALBICOCCA CON PALESTRA - EASY', category: 'EASY' }, 
  { id: 'E203', code: '+POSAE100P.PS-14', label: 'Posa in opera di ALBICOCCA CON SPIRALE E PALESTRA - EASY', category: 'EASY' }, 
  { id: 'E204', code: '+POSAE100PB', label: 'Posa in opera di ALBICOCCABABY CON PALESTRA - EASY', category: 'EASY' }, 
  { id: 'E205', code: '+POSAE101.SVPX-9', label: 'Posa in opera di HOOK - EASY', category: 'EASY' }, 
  { id: 'E206', code: '+POSAE101B.SC1.9.1', label: "Posa in opera di HOOK BABY CON RISALITA FLESSIBILE E PANNELLI ATTIVITA' - EASY", category: 'EASY' }, 
  { id: 'E207', code: '+POSAE101B.SCL1-4', label: 'Posa in opera di HOOK BABY CON RISALITA FLESSIBILE - EASY', category: 'EASY' }, 
  { id: 'E208', code: '+POSAE101B.SVPX-9', label: 'Posa in opera di HOOK BABY CON SARTIA - EASY', category: 'EASY' }, 
  { id: 'E209', code: '+POSAE102', label: 'Posa in opera di PESCA - EASY', category: 'EASY' }, 
  { id: 'E210', code: '+POSAE102.EQ-9', label: 'Posa in opera di PESCA CON TORRE SENZA TETTO - EASY', category: 'EASY' }, 
  { id: 'E211', code: '+POSAE102AP', label: 'Posa in opera di PESCA CON ALTALENA E PALESTRA - EASY', category: 'EASY' }, 
  { id: 'E212', code: '+POSAE102B', label: 'Posa in opera di PESCA BABY - EASY', category: 'EASY' }, 
  { id: 'E213', code: '+POSAE102B.POLY100', label: 'Posa in opera di PESCA BABY CON 2 SCIVOLI - EASY', category: 'EASY' }, 
  { id: 'E214', code: '+POSAE102B.TT-17', label: 'Posa in opera di PESCA BABY CON TUNNEL - EASY', category: 'EASY' }, 
  { id: 'E215', code: '+POSAE102P.PS-14', label: 'Posa in opera di PESCA CON SPIRALE E PALESTRA - EASY', category: 'EASY' }, 
  { id: 'E216', code: '+POSAE102PB', label: 'Posa in opera di PESCA BABY CON PALESTRA - EASY', category: 'EASY' }, 
  { id: 'E217', code: '+POSAE102SSU', label: 'Posa in opera di ANTARES - EASY', category: 'EASY' }, 
  { id: 'E218', code: '+POSAE102SSU.TT-17', label: 'Posa in opera di ARIES - EASY', category: 'EASY' }, 
  { id: 'E219', code: '+POSAE103', label: 'Posa in opera di MANGO - EASY', category: 'EASY' }, 
  { id: 'E220', code: '+POSAE103.S.POLY150', label: 'Posa in opera di MANGO CON SCALA - EASY', category: 'EASY' }, 
  { id: 'E221', code: '+POSAE103.TT-17', label: 'Posa in opera di RIVIERA - EASY', category: 'EASY' }, 
  { id: 'E222', code: '+POSAE103AP', label: 'Posa in opera di MANGO CON ALTALENA E PALESTRA - EASY', category: 'EASY' }, 
  { id: 'E223', code: '+POSAE103PB', label: 'Posa in opera di MANGO BABY - EASY', category: 'EASY' }, 
  { id: 'E224', code: '+POSAC2709SE', label: 'Posa in opera di MALDIVES - FANTASY', category: 'FANTASY' }, 
  { id: 'E225', code: '+POSAC2709SE.PD-5', label: 'Posa in opera di MALDIVES CON PONTE MOBILE - FANTASY', category: 'FANTASY' }, 
  { id: 'E226', code: '+POSAC2709SE.PS-14', label: 'Posa in opera di MALDIVES CON PERTICA SPIRALE - FANTASY', category: 'FANTASY' }, 
  { id: 'E227', code: '+POSAF100', label: 'Posa in opera di FATA - FANTASY', category: 'FANTASY' }, 
  { id: 'E228', code: '+POSAF100.Q-14', label: 'Posa in opera di FATA SENZA TETTO - FANTASY', category: 'FANTASY' }, 
  { id: 'E229', code: '+POSAF100A', label: 'Posa in opera di FATA CON ALTALENA - FANTASY', category: 'FANTASY' }, 
  { id: 'E230', code: '+POSAF100B', label: 'Posa in opera di FATA BABY - FANTASY', category: 'FANTASY' }, 
  { id: 'E231', code: '+POSAF100B.GT-07', label: 'Posa in opera di FATA BABY CON SEDUTA - FANTASY', category: 'FANTASY' }, 
  { id: 'E232', code: '+POSAF100B.PAL-01C', label: 'Posa in opera di FATA BABY 60 CON PALESTRA - FANTASY', category: 'FANTASY' }, 
  { id: 'E233', code: '+POSAF100B.Q-6', label: 'Posa in opera di FATA H60 SENZA TETTO - FANTASY', category: 'FANTASY' }, 
  { id: 'E234', code: '+POSAF100B.Q-9', label: 'Posa in opera di FATA BABY SENZA TETTO - FANTASY', category: 'FANTASY' }, 
  { id: 'E235', code: '+POSAF100B.SG-14', label: 'Posa in opera di FRAGOLA CON PERTICA - FANTASY', category: 'FANTASY' }, 
  { id: 'E236', code: '+POSAF100B.TT-17', label: 'Posa in opera di CILIEGIA - FANTASY', category: 'FANTASY' }, 
  { id: 'E237', code: '+POSAF100P', label: 'Posa in opera di FATA CON PALESTRA - FANTASY', category: 'FANTASY' }, 
  { id: 'E238', code: '+POSAF100PB.SCL1-14', label: "Posa in opera di FATA BABY CON PALESTRA E CLIMBING - FANTASY", category: 'FANTASY' }, 
  { id: 'E239', code: '+POSAF101.EPAL', label: 'Posa in opera di HOOK CON PALESTRA - FANTASY', category: 'FANTASY' }, 
  { id: 'E240', code: '+POSAF101.SG-9', label: 'Posa in opera di HOOK CON SCALA A GRADONI - FANTASY', category: 'FANTASY' }, 
  { id: 'E241', code: '+POSAF101B.ALT-01', label: 'Posa in opera di HOOK BABY CON ALTALENA - FANTASY', category: 'FANTASY' }, 
  { id: 'E242', code: '+POSAF101B.BV-3', label: 'Posa in opera di HOOK BABY 60 - FANTASY', category: 'FANTASY' }, 
  { id: 'E243', code: '+POSAF101B.EPAL', label: 'Posa in opera di HOOK BABY CON PALESTRA - FANTASY', category: 'FANTASY' }, 
  { id: 'E244', code: '+POSAF101B.SVPX-9', label: 'Posa in opera di HOOK BABY CON SCIVOLO - FANTASY', category: 'FANTASY' }, 
  { id: 'E245', code: '+POSAF101E', label: 'Posa in opera di BIBBO - FANTASY', category: 'FANTASY' }, 
  { id: 'E246', code: '+POSAF101E.EF001', label: 'Posa in opera di BIBBO MIRTILLO - FANTASY', category: 'FANTASY' }, 
  { id: 'E247', code: '+POSAF102', label: 'Posa in opera di MERLINO - FANTASY', category: 'FANTASY' }, 
  { id: 'E248', code: '+POSAF102.PI-6', label: 'Posa in opera di MERLINO CON PONTE  - FANTASY', category: 'FANTASY' }, 
  { id: 'E249', code: '+POSAF102.POLY100', label: 'Posa in opera di MERLINO CON SCIVOLO E ARREDO - FANTASY', category: 'FANTASY' }, 
  { id: 'E250', code: '+POSAF102.S1-14', label: 'Posa in opera di MERLINO CON PEDANA DI RISALITA - FANTASY', category: 'FANTASY' }, 
  { id: 'E251', code: '+POSAF102.SG-9', label: 'Posa in opera di MERLINO CON SCALA A GRADONI - FANTASY', category: 'FANTASY' }, 
  { id: 'E252', code: '+POSAF102.SW-14', label: 'Posa in opera di MERLINO CON SCIVOLO A TUBO - FANTASY', category: 'FANTASY' }, 
  { id: 'E253', code: '+POSAF102.SW-14.SVE-14', label: 'Posa in opera di MERLINO CON SCIVOLO E PONTE TIBETANO - FANTASY', category: 'FANTASY' }, 
  { id: 'E254', code: '+POSAF102AP', label: 'Posa in opera di MERLINO CON ALTALENA E PALESTRA - FANTASY', category: 'FANTASY' }, 
  { id: 'E255', code: '+POSAF102B.PD-5', label: 'Posa in opera di MERLINO BABY CON PONTE MOBILE - FANTASY', category: 'FANTASY' }, 
  { id: 'E256', code: '+POSAF102B.SVPX-9', label: 'Posa in opera di MERLINO BABY CON SCIVOLO - FANTASY', category: 'FANTASY' }, 
  { id: 'E257', code: '+POSAF102CN.S-14', label: 'Posa in opera di MERLINO CON SPIRALE - FANTASY', category: 'FANTASY' }, 
  { id: 'E258', code: '+POSAF102P.PD-6', label: 'Posa in opera di MERLINO CON PONTE TIBETANO - FANTASY', category: 'FANTASY' }, 
  { id: 'E259', code: '+POSAF102SSU.PAL-05', label: 'Posa in opera di ANTARES CON PALESTRA SOSPESA - FANTASY', category: 'FANTASY' }, 
  { id: 'E260', code: '+POSAF102SSU.PS-14', label: 'Posa in opera di ARIES BABY - FANTASY', category: 'FANTASY' }, 
  { id: 'E261', code: '+POSAF102SSU.S10', label: 'Posa in opera di ANTARES CON SCALA CURVA - FANTASY', category: 'FANTASY' }, 
  { id: 'E262', code: '+POSAF102SSU.SW-19', label: 'Posa in opera di ARIES   - FANTASY', category: 'FANTASY' }, 
  { id: 'E263', code: '+POSAF102SSU.SWE-14', label: 'Posa in opera di ARIES BABY CON SCIVOLO ELICOIDALE - FANTASY', category: 'FANTASY' }, 
  { id: 'E264', code: '+POSAF103', label: 'Posa in opera di DRAGON - FANTASY', category: 'FANTASY' }, 
  { id: 'E265', code: '+POSAF103.BV-7', label: 'Posa in opera di DRAGON CON TUNNEL E PANNELLI - FANTASY', category: 'FANTASY' }, 
  { id: 'E266', code: '+POSAF103.P-3Q', label: 'Posa in opera di DRAGON CON PANNELLI - FANTASY', category: 'FANTASY' }, 
  { id: 'E267', code: '+POSAF103.PAL-02', label: 'Posa in opera di DRAGON CON PALESTRA RETE - FANTASY', category: 'FANTASY' }, 
  { id: 'E268', code: '+POSAF103.PD-6', label: 'Posa in opera di DRAGON CON PONTE TIBETANO - FANTASY', category: 'FANTASY' }, 
  { id: 'E269', code: '+POSAF103.QT4-19', label: 'Posa in opera di DRAGON H190 - FANTASY', category: 'FANTASY' }, 
  { id: 'E270', code: '+POSAF103A.GT-01', label: 'Posa in opera di DRAGON CON ALTALENA E TRIS - FANTASY', category: 'FANTASY' }, 
  { id: 'E271', code: '+POSAF103B.EPAL-01', label: 'Posa in opera di DRAGON BABY CON PALESTRA - FANTASY', category: 'FANTASY' }, 
  { id: 'E272', code: '+POSAF103B.PD-5', label: 'Posa in opera di DRAGON BABY CON PONTE MOBILE - FANTASY', category: 'FANTASY' }, 
  { id: 'E273', code: '+POSAF103P.TT-17.P-01B', label: 'Posa in opera di DRAGON CON TUNNEL E PALESTRA BABY - FANTASY', category: 'FANTASY' }, 
  { id: 'E274', code: '+POSAF104.TT6-14', label: 'Posa in opera di ROMA CON TORRI TRIANGOLARI - FANTASY', category: 'FANTASY' }, 
  { id: 'E275', code: '+POSAF104K', label: 'Posa in opera di ROMA - FANTASY', category: 'FANTASY' }, 
  { id: 'E276', code: '+POSAF104K.AF100AB', label: 'Posa in opera di ORIONE CON KIT ALTALENA - FANTASY', category: 'FANTASY' }, 
  { id: 'E277', code: '+POSAF104K.ALT-01', label: 'Posa in opera di ROMA CON ALTALENA - FANTASY', category: 'FANTASY' }, 
  { id: 'E278', code: '+POSAF104K.QT4-19', label: 'Posa in opera di ROMA CON SCIVOLO A TUBO  - FANTASY', category: 'FANTASY' }, 
  { id: 'E279', code: '+POSAF104K.SW-19', label: 'Posa in opera di RIVIERA   - FANTASY', category: 'FANTASY' }, 
  { id: 'E280', code: '+POSAF107PB', label: 'Posa in opera di PEGASO - FANTASY', category: 'FANTASY' }, 
  { id: 'E281', code: '+POSAF107PB.SW-14', label: 'Posa in opera di PEGASO CON SCIVOLO A TUBO - FANTASY', category: 'FANTASY' }, 
  { id: 'E282', code: '+POSAF200.STI-14', label: 'Posa in opera di KOS CON PALESTRA ROTANTE - FANTASY', category: 'FANTASY' }, 
  { id: 'E283', code: '+POSAF200.STI-9', label: 'Posa in opera di KOS CON RISALITE - FANTASY', category: 'FANTASY' }, 
  { id: 'E284', code: '+POSAF203', label: 'Posa in opera di CAPRI - FANTASY', category: 'FANTASY' }, 
  { id: 'E285', code: '+POSAF203.PAL-02', label: 'Posa in opera di CAPRI CON PALESTRA - FANTASY', category: 'FANTASY' }, 
  { id: 'E286', code: '+POSAF203.SW-14', label: 'Posa in opera di CAPRI CON SCIVOLO A TUBO - FANTASY', category: 'FANTASY' }, 
  { id: 'E287', code: '+POSAF300H.PI-11', label: 'Posa in opera di SATURNO CON PONTE FISSO - FANTASY', category: 'FANTASY' }, 
  { id: 'E288', code: '+POSAF300H.PI-6', label: 'Posa in opera di SATURNO CON TIBETANO - FANTASY', category: 'FANTASY' }, 
  { id: 'E289', code: '+POSAF300H.S1-14', label: 'Posa in opera di SATURNO CON SCALA E SCIVOLO - FANTASY', category: 'FANTASY' }, 
  { id: 'E290', code: '+POSAF300H.S2-6', label: 'Posa in opera di SATURNO CON PEDANA - FANTASY', category: 'FANTASY' }, 
  { id: 'E291', code: '+POSAF300H.TT-17.BV-7', label: 'Posa in opera di SATURNO CON TUNNEL E PANNELLO MUSICALE - FANTASY', category: 'FANTASY' }, 
  { id: 'E292', code: '+POSAF300R.PS-14', label: 'Posa in opera di NISIDA CON SPIRALE - FANTASY', category: 'FANTASY' }, 
  { id: 'E293', code: '+POSAF301H19', label: 'Posa in opera di SATURNO CON SCIVOLI - FANTASY', category: 'FANTASY' }, 
  { id: 'E294', code: '+POSAF603', label: 'Posa in opera di ELBA - FANTASY', category: 'FANTASY' }, 
  { id: 'E295', code: '+POSAF603B.PD-10', label: 'Posa in opera di ELBA BABY CON PONTE FISSO - FANTASY', category: 'FANTASY' }, 
  { id: 'E296', code: '+POSAF604AP', label: 'Posa in opera di ISCHIA CON ALTALENA E PALESTRA - FANTASY', category: 'FANTASY' }, 
  { id: 'E297', code: '+POSAF604WU', label: 'Posa in opera di ISCHIA CON TUNNEL E SCIVOLO A TUBO - FANTASY', category: 'FANTASY' }, 
  { id: 'E298', code: '+POSAF623', label: 'Posa in opera di PIACENZA - FANTASY', category: 'FANTASY' }, 
  { id: 'E299', code: '+POSAF623.PS-14', label: 'Posa in opera di PIACENZA CON PERTICA SPIRALE - FANTASY', category: 'FANTASY' }, 
  { id: 'E300', code: '+POSAF702FRE19', label: 'Posa in opera di ANDROMEDA - FANTASY', category: 'FANTASY' }, 
  { id: 'E301', code: '+POSAF702FRE19.STI-9', label: 'Posa in opera di ANDROMEDA CON SCIVOLO - FANTASY', category: 'FANTASY' }, 
  { id: 'E302', code: '+POSAF703E2.SCL1-14', label: 'Posa in opera di DRAGON CON PEDANA CLIMBING - FANTASY', category: 'FANTASY' }, 
  { id: 'E303', code: '+POSAF705PAH', label: 'Posa in opera di MECURIO - FANTASY', category: 'FANTASY' }, 
  { id: 'E304', code: '+POSAF705PAH.TT-17', label: 'Posa in opera di MERCURIO CON TUNNEL - FANTASY', category: 'FANTASY' }, 
  { id: 'E305', code: '+POSAL150', label: 'Posa in opera di TORRE MINI - FANTASY', category: 'FANTASY' }, 
  { id: 'E306', code: '+POSAL150.ALT-01', label: 'Posa in opera di TORRE MINI CON ALTALENA - FANTASY', category: 'FANTASY' }, 
  { id: 'E307', code: '+POSAL90', label: 'Posa in opera di TORRE MINI BABY - FANTASY', category: 'FANTASY' }, 
  { id: 'E308', code: '+POSC2.POLY150', label: 'Posa in opera di SCIVOLO PENDIO CON PEDANA - FANTASY', category: 'FANTASY' }, 
  { id: 'E309', code: '+POSS0100', label: 'Posa in opera di SCIVOLO GRANDE - FANTASY', category: 'FANTASY' }, 
  { id: 'E310', code: '+POSS0200', label: 'Posa in opera di SCIVOLO PICCOLO - FANTASY', category: 'FANTASY' }, 
  { id: 'E311', code: '+POSFTR-23', label: 'Posa in opera di HYDRAULIC LEG EXTENTION', category: 'FITNESS' }, 
  { id: 'E312', code: '+POSFTR-24', label: 'Posa in opera di SHOULDER WHEEL', category: 'FITNESS' }, 
  { id: 'E313', code: '+POSFTR-25', label: 'Posa in opera di HYDRAULIC PIGH PULLEY', category: 'FITNESS' }, 
  { id: 'E314', code: '+POSFTR-37', label: 'Posa in opera di HAND CYCLE', category: 'FITNESS' }, 
  { id: 'E315', code: '+POSFTR-38', label: 'Posa in opera di STATIONARY BIKE', category: 'FITNESS' }, 
  { id: 'E316', code: '+POSPV-01', label: 'Posa in opera di TABELLA MOLLEGGIO SULLE GINOCCHIA', category: 'FITNESS' }, 
  { id: 'E317', code: '+POSPV-02', label: 'Posa in opera di PASSAGGIO OSTACOLO SOTTO SOPRA', category: 'FITNESS' }, 
  { id: 'E318', code: '+POSPV-07', label: 'Posa in opera di FUNI DA ARRAMPICATA', category: 'FITNESS' }, 
  { id: 'E319', code: '+POSPV-10', label: 'Posa in opera di IMPIANTO EQUILIBRIO', category: 'FITNESS' }, 
  { id: 'E320', code: '+POSPV-11', label: 'Posa in opera di PULL UP', category: 'FITNESS' }, 
  { id: 'E321', code: '+POSPV-12', label: 'Posa in opera di PANCHE PER ADDOMINALI', category: 'FITNESS' }, 
  { id: 'E322', code: '+POSPV-13', label: 'Posa in opera di SENTIERO PALIZZATE', category: 'FITNESS' }, 
  { id: 'E323', code: '+POSPV-14', label: 'Posa in opera di SENTIERO SLALOM', category: 'FITNESS' }, 
  { id: 'E324', code: '+POSPV-16', label: 'Posa in opera di CORSA OSTACOLI', category: 'FITNESS' }, 
  { id: 'E325', code: '+POSPV-17', label: 'Posa in opera di MURO DI ARRAMPICATA', category: 'FITNESS' }, 
  { id: 'E326', code: '+POSPV-19', label: 'Posa in opera di ANELLI', category: 'FITNESS' }, 
  { id: 'E327', code: '+POSPV-20', label: 'Posa in opera di ASSE EQUILIBRIO INCLINATA', category: 'FITNESS' }, 
  { id: 'E328', code: '+POSPV-21', label: 'Posa in opera di ASSE EQUILIBRIO DRITTA', category: 'FITNESS' }, 
  { id: 'E329', code: '+POSPV-22', label: 'Posa in opera di PANCA INCLINATA', category: 'FITNESS' }, 
  { id: 'E330', code: '+POSPV-23', label: 'Posa in opera di PANCA PIANA', category: 'FITNESS' }, 
  { id: 'E331', code: '+POSPV-24', label: 'Posa in opera di PARALLELE', category: 'FITNESS' }, 
  { id: 'E332', code: '+POSPV-25', label: 'Posa in opera di SALTO A OSTACOLI', category: 'FITNESS' }, 
  { id: 'E333', code: '+POSPV-26', label: 'Posa in opera di SENIERO A OSTACOLI', category: 'FITNESS' }, 
  { id: 'E334', code: '+POSPV-28', label: 'Posa in opera di ASSE OSTACOLO', category: 'FITNESS' }, 
  { id: 'E335', code: '+POSPV-29', label: 'Posa in opera di TRONCO OSCILLANTE', category: 'FITNESS' }, 
  { id: 'E336', code: '+POSPV-30', label: 'Posa in opera di PEDANA STEP', category: 'FITNESS' }, 
  { id: 'E337', code: '+POSC8000', label: 'Posa in opera di TORRE PIRAMIDALE GIREVOLE', category: 'GIOCHI' }, 
  { id: 'E338', code: '+POSG0050', label: 'Posa in opera di PALO ROTANTE', category: 'GIOCHI' }, 
  { id: 'E339', code: '+POSG0100', label: 'Posa in opera di GIOSTRA GIROTONDO PICCOLA', category: 'GIOCHI' }, 
  { id: 'E340', code: '+POSG0100.I0680', label: 'Posa in opera di GIOSTRA GIROTONDO MARGHERITA', category: 'GIOCHI' }, 
  { id: 'E341', code: '+POSG0300', label: 'Posa in opera di GIOSTRA GIROTONDO GRANDE', category: 'GIOCHI' }, 
  { id: 'E342', code: '+POSG0300.3', label: 'Posa in opera di ROUND', category: 'GIOCHI' }, 
  { id: 'E343', code: '+POSG0300.4', label: 'Posa in opera di AMACA ROTANTE', category: 'GIOCHI' }, 
  { id: 'E344', code: '+POSG0300.GT-06B', label: 'Posa in opera di SPINNER TULIPANO', category: 'GIOCHI' }, 
  { id: 'E345', code: '+POSG0300H1', label: 'Posa in opera di GIOSTRA GIROTONDO INCLUSIVE', category: 'GIOCHI' }, 
  { id: 'E346', code: '+POSG0300H1.1', label: 'Posa in opera di GIOSTRA GIROTONDO INCLUSIVE MINIMAL', category: 'GIOCHI' }, 
  { id: 'E347', code: '+POSG0400', label: 'Posa in opera di GIOSTRA MOUSE', category: 'GIOCHI' }, 
  { id: 'E348', code: '+POSG0600', label: 'Posa in opera di GIOSTRA A TUBI', category: 'GIOCHI' }, 
  { id: 'E349', code: '+POSJ06001R', label: 'Posa in opera di ELLISSE ROTANTE', category: 'GIOCHI' }, 
  { id: 'E350', code: '+POSJ07001R', label: 'Posa in opera di GRILLO ROTANTE', category: 'GIOCHI' }, 
  { id: 'E351', code: '+POSJ08001R', label: 'Posa in opera di TRIANGLE ROTANTE', category: 'GIOCHI' }, 
  { id: 'E352', code: '+POSF0100.J02001', label: 'Posa in opera di DONDOLO A MOLLA LEONE', category: 'GIOCHI A MOLLA' }, 
  { id: 'E353', code: '+POSF0100.J02003', label: 'Posa in opera di DONDOLO A MOLLA BALENA', category: 'GIOCHI A MOLLA' }, 
  { id: 'E354', code: '+POSF103', label: 'Posa in opera di DONDOLO QUADRIFOGLIO', category: 'GIOCHI A MOLLA' }, 
  { id: 'E355', code: '+POSJ01001', label: 'Posa in opera di SCOIATTOLO', category: 'GIOCHI A MOLLA' }, 
  { id: 'E356', code: '+POSJ01001.GT-06', label: 'Posa in opera di GIOCO A MOLLA STEP', category: 'GIOCHI A MOLLA' }, 
  { id: 'E357', code: '+POSJ01001.U0600.0', label: 'Posa in opera di GIOCO A MOLLA OPTICAL', category: 'GIOCHI A MOLLA' }, 
  { id: 'E358', code: '+POSJ01001_P', label: 'Posa in opera di CAVALLO', category: 'GIOCHI A MOLLA' }, 
  { id: 'E359', code: '+POSJ01002', label: 'Posa in opera di GIRAFFA', category: 'GIOCHI A MOLLA' }, 
  { id: 'E360', code: '+POSJ01003', label: 'Posa in opera di CONIGLIO', category: 'GIOCHI A MOLLA' }, 
  { id: 'E361', code: '+POSJ01006', label: 'Posa in opera di CAMMELLO', category: 'GIOCHI A MOLLA' }, 
  { id: 'E362', code: '+POSJ01006.1', label: 'Posa in opera di UNICORNO', category: 'GIOCHI A MOLLA' }, 
  { id: 'E363', code: '+POSJ02001', label: 'Posa in opera di LEONE', category: 'GIOCHI A MOLLA' }, 
  { id: 'E364', code: '+POSJ02001.1', label: 'Posa in opera di RACECAR', category: 'GIOCHI A MOLLA' }, 
  { id: 'E365', code: '+POSJ02001.2', label: 'Posa in opera di COCCODRILLO', category: 'GIOCHI A MOLLA' }, 
  { id: 'E366', code: '+POSJ02001.3_P', label: 'Posa in opera di CHIOCCIOLA', category: 'GIOCHI A MOLLA' }, 
  { id: 'E367', code: '+POSJ02001.4', label: 'Posa in opera di BOB', category: 'GIOCHI A MOLLA' }, 
  { id: 'E368', code: '+POSJ02001.5', label: 'Posa in opera di TAVOLOZZA', category: 'GIOCHI A MOLLA' }, 
  { id: 'E369', code: '+POSJ02002', label: 'Posa in opera di GORILLA', category: 'GIOCHI A MOLLA' }, 
  { id: 'E370', code: '+POSJ02003', label: 'Posa in opera di BALENA', category: 'GIOCHI A MOLLA' }, 
  { id: 'E371', code: '+POSJ02004', label: 'Posa in opera di SOTTOMARINO', category: 'GIOCHI A MOLLA' }, 
  { id: 'E372', code: '+POSJ03001', label: 'Posa in opera di ORSETTO TANDEM', category: 'GIOCHI A MOLLA' }, 
  { id: 'E373', code: '+POSJ03002', label: 'Posa in opera di PAPPAGALLO TANDEM', category: 'GIOCHI A MOLLA' }, 
  { id: 'E374', code: '+POSJ07001', label: 'Posa in opera di GRILLO', category: 'GIOCHI A MOLLA' }, 
  { id: 'E375', code: '+POSJ07001.1', label: 'Posa in opera di JEEP', category: 'GIOCHI A MOLLA' }, 
  { id: 'E376', code: '+POSJ09001', label: 'Posa in opera di NIDO A MOLLA', category: 'GIOCHI A MOLLA' }, 
  { id: 'E377', code: '+POSAB102GS', label: 'Posa in opera di ARCA WINNIE', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E378', code: '+POSAF102.P-7_M', label: 'Posa in opera di MERLINO MEDIEVAL FANTASY', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E379', code: '+POSAR100', label: 'Posa in opera di ARCA', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E380', code: '+POSAR102W', label: 'Posa in opera di ANIMAL BOAT', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E381', code: '+POSAS100BGS', label: 'Posa in opera di ALBICOCCO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E382', code: '+POSAS100BGS.POLY150', label: 'Posa in opera di ALBICOCCO 3 TORRI', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E383', code: '+POSAS100BGS.S-9', label: 'Posa in opera di ALBICOCCO 2 TORRI CON SCALA', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E384', code: '+POSAS102.TT-17', label: 'Posa in opera di GIOCO BRUCO DUE TORRI', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E385', code: '+POSAS103.TT-17', label: 'Posa in opera di GIOCO BRUCO TRE TORRI', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E386', code: '+POSAS104.TT-17', label: 'Posa in opera di GIOCO BRUCO QUATTRO TORRI', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E387', code: '+POSB06', label: 'Posa in opera di BRUCO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E388', code: '+POSB07', label: 'Posa in opera di SOLE', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E389', code: '+POSB09', label: 'Posa in opera di MEZZE SFERE', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E390', code: '+POSC02TP', label: 'Posa in opera di REPTILE CON TUBO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E391', code: '+POSC0500.P-3Q', label: 'Posa in opera di SERPENTE GIOVANNI', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E392', code: '+POSC0500.PAL-01C', label: 'Posa in opera di KRAKEN', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E393', code: '+POSC0500.PAL-06.SW-14', label: 'Posa in opera di TORRE PALESTRA PICCOLA', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E394', code: '+POSC0500.PAL-06.SW-19', label: 'Posa in opera di TORRE PALESTRA DOPPIA', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E395', code: '+POSC0500.PAL-06.SWE-14', label: 'Posa in opera di TORRE PALESTRA MEDIA', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E396', code: '+POSC0500.PAL-08B', label: 'Posa in opera di DRAGO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E397', code: '+POSC0500.S6-14', label: 'Posa in opera di GRILLO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E398', code: '+POSC0500.S6-9', label: 'Posa in opera di RAGNO GIORGIO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E399', code: '+POSC0500.SW-14', label: 'Posa in opera di FARFALLA', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E400', code: '+POSC0800-PAL-06', label: 'Posa in opera di TORRE PALESTRA GRANDE', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E401', code: '+POSC33', label: 'Posa in opera di CAPYBARA', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E402', code: '+POSC38TP', label: 'Posa in opera di CAMALEONTE CON TUBO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E403', code: '+POSE07', label: 'Posa in opera di COLLINA XL', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E404', code: '+POSE16P', label: 'Posa in opera di METEORITE', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E405', code: '+POSE17-L', label: 'Posa in opera di COLLINA', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E406', code: '+POSFF300', label: 'Posa in opera di TRENO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E407', code: '+POSFF300.SVPX-14', label: 'Posa in opera di CARROZZA TRENO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E408', code: '+POSFF300B', label: 'Posa in opera di TRENO BABY', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E409', code: '+POSGS100', label: 'Posa in opera di RIFUGIO SULL\'ALBERO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E410', code: '+POSM01', label: 'Posa in opera di APE MINI', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E411', code: '+POSM10', label: 'Posa in opera di TARTARUGA MINI', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E412', code: '+POSM12', label: 'Posa in opera di POLPO MINI', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E413', code: '+POSM16', label: 'Posa in opera di WORM', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E414', code: '+POSS0400B', label: 'Posa in opera di SCIVOLO ELEFANTE BABY', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E415', code: '+POSS0600', label: 'Posa in opera di SCIVOLO BALENA BABY', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E416', code: '+POSS0700', label: 'Posa in opera di SCIVOLO GIRAFFA', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E417', code: '+POSS0800_P', label: 'Posa in opera di SCIVOLO T-REX PRIMITIV', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E418', code: '+POSS800.ALT01PAL01_L', label: 'Posa in opera di SCIVOLO T-REX CON ALTALENA E PALESTRA LEAVES', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E419', code: '+POSV0100.GT-04', label: 'Posa in opera di CAMIONCINO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E420', code: '+POSV0300.GT-01', label: 'Posa in opera di JUNGLE CORNER', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E421', code: '+POSV0500', label: 'Posa in opera di MOBY DICK', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E422', code: '+POSV0600.ABACOU0700_P', label: 'Posa in opera di BARCHETTA CON TIMONE', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E423', code: '+POSV0600.AF101.SVPX-6', label: 'Posa in opera di SOTTOMARINO BABY', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E424', code: '+POSV0600.AF101B', label: 'Posa in opera di BARCHETTA A VELA', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E425', code: '+POSV0600.AF101B.S-9', label: 'Posa in opera di AEREO BABY', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E426', code: '+POSV0600.GT-01', label: 'Posa in opera di CARAVELLA TRIS', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E427', code: '+POSV0600.SVPX-14', label: 'Posa in opera di CARAVELLA CON SCIVOLO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E428', code: '+POSV0600.SW-14_P', label: 'Posa in opera di CARAVELLA PRIMITIV CON SCIVOLO A TUBO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E429', code: '+POSV0700.SW-19', label: 'Posa in opera di GALEONE CON SCIVOLO A TUBO', category: 'GIOCHI SCENOGRAFICI' }, 
  { id: 'E430', code: '+POSAF101B.EPAL_L', label: 'Posa in opera di HOOK BABY CON PALESTRA - LEAVES', category: 'LEAVES' }, 
  { id: 'E431', code: '+POSAF101B.SVPX-6_L', label: 'Posa in opera di HOOK BABY CON SCIVOLO 60 - LEAVES', category: 'LEAVES' }, 
  { id: 'E432', code: '+POSAF101B.SVPX-9_L', label: 'Posa in opera di HOOK BABY CON SCIVOLO - LEAVES', category: 'LEAVES' }, 
  { id: 'E433', code: '+POSAF102.PI-6_L', label: 'Posa in opera di MERLINO CON PONTE TIBETANO - LEAVES', category: 'LEAVES' }, 
  { id: 'E434', code: '+POSAF102.POLY100_L', label: 'Posa in opera di MERLINO CON SCIVOLO E ARREDO - LEAVES', category: 'LEAVES' }, 
  { id: 'E435', code: '+POSAF102.S1-14_L', label: 'Posa in opera di MERLINO CON PEDANA DI RISALITA - LEAVES', category: 'LEAVES' }, 
  { id: 'E436', code: '+POSAF102.SG-9_L', label: 'Posa in opera di MERLINO CON SCALA A GRADONI - LEAVES', category: 'LEAVES' }, 
  { id: 'E437', code: '+POSAF102.SW-14.SVE-14_L', label: 'Posa in opera di MERLINO CON SCIVOLO E PONTE TIBETANO - LEAVES', category: 'LEAVES' }, 
  { id: 'E438', code: '+POSAF102.SW-14_L', label: 'Posa in opera di MERLINO CON SCIVOLO A TUBO - LEAVES', category: 'LEAVES' }, 
  { id: 'E439', code: '+POSAF102_L', label: 'Posa in opera di MERLINO - LEAVES', category: 'LEAVES' }, 
  { id: 'E440', code: '+POSAF102AP_L', label: 'Posa in opera di MERLINO CON ALTALENA E PALESTRA - LEAVES', category: 'LEAVES' }, 
  { id: 'E441', code: '+POSAF102B.PD-5_L', label: 'Posa in opera di MERLINO BABY CON PONTE MOBILE - LEAVES', category: 'LEAVES' }, 
  { id: 'E442', code: '+POSAF102CN.S-14_L', label: 'Posa in opera di MERLINO CON SPIRALE - LEAVES', category: 'LEAVES' }, 
  { id: 'E443', code: '+POSAF102SSU.PAL-05_L', label: 'Posa in opera di ANTARES CON PALESTRA - LEAVES', category: 'LEAVES' }, 
  { id: 'E444', code: '+POSAF102SSU.PS-14_L', label: 'Posa in opera di ARIES BABY - LEAVES', category: 'LEAVES' }, 
  { id: 'E445', code: '+POSAF102SSU.S10_L', label: 'Posa in opera di ANTARES CON SCALA CURVA - LEAVES', category: 'LEAVES' }, 
  { id: 'E446', code: '+POSAF102SSU.SW-19_L', label: 'Posa in opera di ARIES - LEAVES', category: 'LEAVES' }, 
  { id: 'E447', code: '+POSAF103.BV-7_L', label: 'Posa in opera di DRAGON CON TUNNEL E PANNELLI - LEAVES', category: 'LEAVES' }, 
  { id: 'E448', code: '+POSAF103.P-3Q_L', label: 'Posa in opera di DRAGON CON PANNELLI - LEAVES', category: 'LEAVES' }, 
  { id: 'E449', code: '+POSAF103.PAL-02_L', label: 'Posa in opera di DRAGON CON PALESTRA RETE - LEAVES', category: 'LEAVES' }, 
  { id: 'E450', code: '+POSAF103.PD-6_L', label: 'Posa in opera di DRAGON CON PONTE TIBETANO - LEAVES', category: 'LEAVES' }, 
  { id: 'E451', code: '+POSAF103.QT4-19_L', label: 'Posa in opera di DRAGON H190 - LEAVES', category: 'LEAVES' }, 
  { id: 'E452', code: '+POSAF103AP.GT-01_L', label: 'Posa in opera di DRAGON CON ALTALENA PALESTRA E TRIS - LEAVES', category: 'LEAVES' }, 
  { id: 'E453', code: '+POSAF103B.EPAL-01_L', label: 'Posa in opera di DRAGON BABY CON PALESTRA - LEAVES', category: 'LEAVES' }, 
  { id: 'E454', code: '+POSAF103B.PD-5_L', label: 'Posa in opera di DRAGON BABY CON PONTE MOBILE - LEAVES', category: 'LEAVES' }, 
  { id: 'E455', code: '+POSAF103P.TT-17.P-01b_L', label: 'Posa in opera di DRAGON CON TUNNEL E PALESTRA BABY - LEAVES', category: 'LEAVES' }, 
  { id: 'E456', code: '+POSAF103P_L', label: 'Posa in opera di DRAGON CON PALESTRA - LEAVES', category: 'LEAVES' }, 
  { id: 'E457', code: '+POSAF104.TT6-14_L', label: 'Posa in opera di ROMA CON TORRI TRIANGOLARI - LEAVES', category: 'LEAVES' }, 
  { id: 'E458', code: '+POSAF104K.AF100AB_L', label: 'Posa in opera di ORIONE CON KIT ALTALENA - LEAVES', category: 'LEAVES' }, 
  { id: 'E459', code: '+POSAF104K.QT4-19_L', label: 'Posa in opera di ROMA CON SCIVOLO A TUBO - LEAVES', category: 'LEAVES' }, 
  { id: 'E460', code: '+POSAF104K.SW-19_L', label: 'Posa in opera di RIVIERA - LEAVES', category: 'LEAVES' }, 
  { id: 'E461', code: '+POSAF104K_L', label: 'Posa in opera di ROMA - LEAVES', category: 'LEAVES' }, 
  { id: 'E462', code: '+POSAF107PB.SW-14_L', label: 'Posa in opera di PEGASO CON SCIVOLO A TUBO - LEAVES', category: 'LEAVES' }, 
  { id: 'E463', code: '+POSAF107Pb_L', label: 'Posa in opera di PEGASO - LEAVES', category: 'LEAVES' }, 
  { id: 'E464', code: '+POSAF200.STI-14_L', label: 'Posa in opera di KOS CON PALESTRA ROTANTE - LEAVES', category: 'LEAVES' }, 
  { id: 'E465', code: '+POSAF200.STI-9_L', label: 'Posa in opera di KOS CON RISALITE - LEAVES', category: 'LEAVES' }, 
  { id: 'E466', code: '+POSAF203.PAL-02_L', label: 'Posa in opera di CAPRI CON PALESTRA - LEAVES', category: 'LEAVES' }, 
  { id: 'E467', code: '+POSAF203.SW-14_L', label: 'Posa in opera di CAPRI CON SCIVOLO A TUBO - LEAVES', category: 'LEAVES' }, 
  { id: 'E468', code: '+POSAF203_L', label: 'Posa in opera di CAPRI - LEAVES', category: 'LEAVES' }, 
  { id: 'E469', code: '+POSAF300H.PI-11_L', label: 'Posa in opera di SATURNO CON PONTE FISSO - LEAVES', category: 'LEAVES' }, 
  { id: 'E470', code: '+POSAF300H.PI-6_L', label: 'Posa in opera di SATURNO CON TIBETANO - LEAVES', category: 'LEAVES' }, 
  { id: 'E471', code: '+POSAF300H.S1-14_L', label: 'Posa in opera di SATURNO CON SCALA E SCIVOLO - LEAVES', category: 'LEAVES' }, 
  { id: 'E472', code: '+POSAF300H.S2-6_L', label: 'Posa in opera di SATURNO CON PEDANA - LEAVES', category: 'LEAVES' }, 
  { id: 'E473', code: '+POSAF300H.TT-17.BV-7_L', label: 'Posa in opera di SATURNO CON TUNNEL E PANNELLO MUSICALE - LEAVES', category: 'LEAVES' }, 
  { id: 'E474', code: '+POSAF300R.PS-14_L', label: 'Posa in opera di NISIDA CON SPIRALE - LEAVES', category: 'LEAVES' }, 
  { id: 'E475', code: '+POSAF301H19_L', label: 'Posa in opera di SATURNO CON SCIVOLI - LEAVES', category: 'LEAVES' }, 
  { id: 'E476', code: '+POSAF603_L', label: 'Posa in opera di ELBA - LEAVES', category: 'LEAVES' }, 
  { id: 'E477', code: '+POSAF603B.PD-10_L', label: 'Posa in opera di ELBA BABY CON PONTE FISSO - LEAVES', category: 'LEAVES' }, 
  { id: 'E478', code: '+POSAF604AP_L', label: 'Posa in opera di ISCHIA CON ALTALENA E PALESTRA - LEAVES', category: 'LEAVES' }, 
  { id: 'E479', code: '+POSAF604WU_L', label: 'Posa in opera di ISCHIA CON TUNNEL E SCIVOLO A TUBO - LEAVES', category: 'LEAVES' }, 
  { id: 'E480', code: '+POSAF623_L', label: 'Posa in opera di PIACENZA - LEAVES', category: 'LEAVES' }, 
  { id: 'E481', code: '+POSAF702FRE19.STI-9_L', label: 'Posa in opera di ANDROMEDA CON SCIVOLO A TUBO - LEAVES', category: 'LEAVES' }, 
  { id: 'E482', code: '+POSAF702FRE19_L', label: 'Posa in opera di ANDROMEDA - LEAVES', category: 'LEAVES' }, 
  { id: 'E483', code: '+POSAF703E2.SCL1-14_L', label: 'Posa in opera di DRAGON CON PEDANA CLIMBING - LEAVES', category: 'LEAVES' }, 
  { id: 'E484', code: '+POSAF705PAH.TT-17_L', label: 'Posa in opera di MERCURIO CON TUNNEL - LEAVES', category: 'LEAVES' }, 
  { id: 'E485', code: '+POSAF705PAH_L', label: 'Posa in opera di MERCURIO - LEAVES', category: 'LEAVES' }, 
  { id: 'E486', code: '+POSAL150.ALT-01_L', label: 'Posa in opera di TORRE MINI CON ALTALENA - LEAVES', category: 'LEAVES' }, 
  { id: 'E487', code: '+POSAL150_L', label: 'Posa in opera di TORRE MINI - LEAVES', category: 'LEAVES' }, 
  { id: 'E488', code: '+POSAL90_L', label: 'Posa in opera di TORRE MINI BABY - LEAVES', category: 'LEAVES' }, 
  { id: 'E489', code: '+POSS0100_L', label: 'Posa in opera di SCIVOLO GRANDE - LEAVES', category: 'LEAVES' }, 
  { id: 'E490', code: '+POSS0200_L', label: 'Posa in opera di SCIVOLO PICCOLO - LEAVES', category: 'LEAVES' }, 
  { id: 'E491', code: '+POSAC2709SE.PD-5_L', label: 'Posa in opera di MALDIVES CON PONTE MOBILE - LEAVES', category: 'LEAVES' }, 
  { id: 'E492', code: '+POSAC2709SE.PS-14_L', label: 'Posa in opera di MALDIVES CON PERTICA SPIRALE - LEAVES', category: 'LEAVES' }, 
  { id: 'E493', code: '+POSAC2709SE_L', label: 'Posa in opera di MALDIVES - LEAVES', category: 'LEAVES' }, 
  { id: 'E494', code: '+POSAF100_L', label: 'Posa in opera di FATA - LEAVES', category: 'LEAVES' }, 
  { id: 'E495', code: '+POSAF100A_L', label: 'Posa in opera di FATA CON ALTALENA - LEAVES', category: 'LEAVES' }, 
  { id: 'E496', code: '+POSAF100B.GT-07_L', label: 'Posa in opera di FATA BABY CON SEDUTA - LEAVES', category: 'LEAVES' }, 
  { id: 'E497', code: '+POSAF100B.PAL-01C_L', label: 'Posa in opera di FATA BABY 60 CON PALESTRA - LEAVES', category: 'LEAVES' }, 
  { id: 'E498', code: '+POSAF100B.Q-6_L', label: 'Posa in opera di FATA H60 SENZA TETTO - LEAVES', category: 'LEAVES' }, 
  { id: 'E499', code: '+POSAF100B.Q-9_L', label: 'Posa in opera di FATA BABY SENZA TETTO - LEAVES', category: 'LEAVES' }, 
  { id: 'E500', code: '+POSAF100B.SG-14_L', label: 'Posa in opera di FRAGOLA CON PERTICA - LEAVES', category: 'LEAVES' }, 
  { id: 'E501', code: '+POSAF100B.TT-17_L', label: 'Posa in opera di CILIEGIA - LEAVES', category: 'LEAVES' }, 
  { id: 'E502', code: '+POSAF100B_L', label: 'Posa in opera di FATA BABY - LEAVES', category: 'LEAVES' }, 
  { id: 'E503', code: '+POSAF100P_L', label: 'Posa in opera di FATA CON PALESTRA - LEAVES', category: 'LEAVES' }, 
  { id: 'E504', code: '+POSAF100PB.SCL1-14_L', label: 'Posa in opera di FATA BABY CON PALESTRA - LEAVES', category: 'LEAVES' }, 
  { id: 'E505', code: '+POSAF101.EPAL_L', label: 'Posa in opera di HOOK CON PALESTRA - LEAVES', category: 'LEAVES' }, 
  { id: 'E506', code: '+POSAF101.SG-9_L', label: 'Posa in opera di HOOK CON SCALA A GRADONI - LEAVES', category: 'LEAVES' }, 
  { id: 'E507', code: '+POSAF101B.ALT-01_L', label: 'Posa in opera di HOOK BABY CON ALTALENA - LEAVES', category: 'LEAVES' }, 
  { id: 'E508', code: '+POSAF101B.BV-3_L', label: 'Posa in opera di HOOK BABY 60 - LEAVES', category: 'LEAVES' }, 
  { id: 'E509', code: '+POSAC2709SE.PD-5_M', label: 'Posa in opera di MALDIVES CON PONTE - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E510', code: '+POSAF100.PP-14_M', label: 'Posa in opera di FATA CON PALO POMPIERI - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E511', code: '+POSAF100_M', label: 'Posa in opera di FATA - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E512', code: '+POSAF101.SVPX-9_M', label: 'Posa in opera di HOOK CON SCIVOLO - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E513', code: '+POSAF102.P-2_M', label: 'Posa in opera di MERLINO BABY - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E514', code: '+POSAF102.S-9_M', label: 'Posa in opera di MERLINO CON SCALA H90 - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E515', code: '+POSAF102_M', label: 'Posa in opera di MERLINO - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E516', code: '+POSAF103_M', label: 'Posa in opera di DRAGON - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E517', code: '+POSAF103P_M', label: 'Posa in opera di DRAGON CON PALESTRA - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E518', code: '+POSAF104K.S-14_M', label: 'Posa in opera di ROMA CON PONTE TIBETANO - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E519', code: '+POSAF104K_M', label: 'Posa in opera di ROMA - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E520', code: '+POSAF603_M', label: 'Posa in opera di ELBA - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E521', code: '+POSAF802.SVPX-14_M', label: 'Posa in opera di GIULIETTA E ROMEO - MEDIEVAL', category: 'MEDIEVAL' }, 
  { id: 'E522', code: '+POSAF100.U0100.PAL-10_P', label: 'Posa in opera di FATA CON PERCORSO FUNI', category: 'PALESTRE' }, 
  { id: 'E523', code: '+POSAF102.C0100', label: 'Posa in opera di ALUGYM 2', category: 'PALESTRE' }, 
  { id: 'E524', code: '+POSAF200.T-9', label: 'Posa in opera di KOS CON TUNNEL TIBETANO', category: 'PALESTRE' }, 
  { id: 'E525', code: '+POSC0100', label: 'Posa in opera di PALESTRA ESAGONALE', category: 'PALESTRE' }, 
  { id: 'E526', code: '+POSC0200', label: 'Posa in opera di PALESTRA LINEARE', category: 'PALESTRE' }, 
  { id: 'E527', code: '+POSC0300', label: 'Posa in opera di PALESTRA CUBO', category: 'PALESTRE' }, 
  { id: 'E528', code: '+POSC0300.C0100_P', label: 'Posa in opera di SPIDER GYM 1', category: 'PALESTRE' }, 
  { id: 'E529', code: '+POSC0300.C0200_P', label: 'Posa in opera di SPIDER GYM 2', category: 'PALESTRE' }, 
  { id: 'E530', code: '+POSC0300.C0400', label: 'Posa in opera di PALESTRA CUBO BABY', category: 'PALESTRE' }, 
  { id: 'E531', code: '+POSC0300.C0400.2_P', label: 'Posa in opera di SPIDER GYM CON RETI', category: 'PALESTRE' }, 
  { id: 'E532', code: '+POSC0300.C0400_P', label: 'Posa in opera di SPIDER GYM 4', category: 'PALESTRE' }, 
  { id: 'E533', code: '+POSC0300.PAL-05', label: 'Posa in opera di PALESTRA HULA HOP', category: 'PALESTRE' }, 
  { id: 'E534', code: '+POSC0400', label: 'Posa in opera di PALESTRA TRIANGOLO', category: 'PALESTRE' }, 
  { id: 'E535', code: '+POSC0500', label: 'Posa in opera di PALESTRA MINI CUBO', category: 'PALESTRE' }, 
  { id: 'E536', code: '+POSC0500.PAL-04', label: 'Posa in opera di PALESTRA OVALE', category: 'PALESTRE' }, 
  { id: 'E537', code: '+POSC0500.PAL-05', label: 'Posa in opera di PALESTRA AD ARCO', category: 'PALESTRE' }, 
  { id: 'E538', code: '+POSC0500.S-10-14', label: 'Posa in opera di PALESTRA SKYLINE1', category: 'PALESTRE' }, 
  { id: 'E539', code: '+POSC0600', label: 'Posa in opera di SARTIA 01', category: 'PALESTRE' }, 
  { id: 'E540', code: '+POSC0600.B', label: 'Posa in opera di SARTIA BABY', category: 'PALESTRE' }, 
  { id: 'E541', code: '+POSC0600.B_P', label: 'Posa in opera di SARTIA BABY PRIMITIV', category: 'PALESTRE' }, 
  { id: 'E542', code: '+POSC0600.PAL-08', label: 'Posa in opera di SARTIA PIRAMIDE', category: 'PALESTRE' }, 
  { id: 'E543', code: '+POSC0800', label: 'Posa in opera di BLOCCO CLIMBING', category: 'PALESTRE' }, 
  { id: 'E544', code: '+POSC0800.C', label: 'Posa in opera di BLOCCO CLIMBING DOPPIO', category: 'PALESTRE' }, 
  { id: 'E545', code: '+POSC0800.P-3', label: 'Posa in opera di PALESTRA MULTIPIANO', category: 'PALESTRE' }, 
  { id: 'E546', code: '+POSC0800.PAL-01', label: 'Posa in opera di PALESTRA RETE ARRAMPICATA SOSPESA', category: 'PALESTRE' }, 
  { id: 'E547', code: '+POSC0800.PAL-02', label: 'Posa in opera di PALESTRA RETE ARRAMPICATA SCIVOLO', category: 'PALESTRE' }, 
  { id: 'E548', code: '+POSC0800.PAL-03', label: 'Posa in opera di PALESTRA RETE ARRAMPICATA ROTONDA', category: 'PALESTRE' }, 
  { id: 'E549', code: '+POSC0800.PAL-04', label: 'Posa in opera di PALESTRA RETE ARRAMPICATA GRANDE', category: 'PALESTRE' }, 
  { id: 'E550', code: '+POSC0800.SCL1-14', label: 'Posa in opera di PALESTRA PIRAMIDE ARRAMPICATA', category: 'PALESTRE' }, 
  { id: 'E551', code: '+POSC0800.SCL1-14.1', label: 'Posa in opera di PALESTRA PIRAMIDE ARRAMPICATA SINGOLA', category: 'PALESTRE' }, 
  { id: 'E552', code: '+POSC0800.SCL1-14.2', label: 'Posa in opera di PALESTRA PIRAMIDE ARRAMPICATA DOPPIA', category: 'PALESTRE' }, 
  { id: 'E553', code: '+POSC0800.SCL1-19', label: 'Posa in opera di PALESTRA PIRAMIDE', category: 'PALESTRE' }, 
  { id: 'E554', code: '+POSC1000', label: 'Posa in opera di PALESTRA MILLE CUBI', category: 'PALESTRE' }, 
  { id: 'E555', code: '+POSE0200.SCL1-14', label: 'Posa in opera di CAPANNA CLIMBING', category: 'PALESTRE' }, 
  { id: 'E556', code: '+POSEPAL', label: 'Posa in opera di PALESTRA EASY', category: 'PALESTRE' }, 
  { id: 'E557', code: '+POSEPAL.PS14', label: 'Posa in opera di EASY GYM 3', category: 'PALESTRE' }, 
  { id: 'E558', code: '+POSGT-06.U0100_P', label: 'Posa in opera di PALESTRA NEST PRIMITIV', category: 'PALESTRE' }, 
  { id: 'E559', code: '+POSGT-06_P', label: 'Posa in opera di STEP PRIMITIV', category: 'PALESTRE' }, 
  { id: 'E560', code: '+POSGT-06B.1_P', label: 'Posa in opera di STEP PRIMITIV ALTO', category: 'PALESTRE' }, 
  { id: 'E561', code: '+POSGT-06B.2_P', label: 'Posa in opera di PERCORSO STEP 1', category: 'PALESTRE' }, 
  { id: 'E562', code: '+POSGT-06B.3_P', label: 'Posa in opera di STEP TRONCO', category: 'PALESTRE' }, 
  { id: 'E563', code: '+POSGT-06B.4_P', label: 'Posa in opera di STEP TRONCHI PRIMITIV', category: 'PALESTRE' }, 
  { id: 'E564', code: '+POSGT-06B.5_P', label: 'Posa in opera di PERCORSO EQUILIBRIO PRIMITIV', category: 'PALESTRE' }, 
  { id: 'E565', code: '+POSGT-06B.C0100_P', label: 'Posa in opera di STEP 2', category: 'PALESTRE' }, 
  { id: 'E566', code: '+POSGT-06B_P', label: 'Posa in opera di STEP PRIMITIV BABY', category: 'PALESTRE' }, 
  { id: 'E567', code: '+POSHEX-3', label: 'Posa in opera di TRAMPOLINO TRIPLO', category: 'PALESTRE' }, 
  { id: 'E568', code: '+POSPAL-08.P-3Q', label: 'Posa in opera di EASY GYM BABY 5', category: 'PALESTRE' }, 
  { id: 'E568', code: '+POSPAL-08.SCL1-14', label: 'Posa in opera di PALESTRA LINEA', category: 'PALESTRE' }, 
  { id: 'E570', code: '+POSPAL-08.SCL1-14.PP14', label: 'Posa in opera di PALESTRA CON PALO POMPIERI', category: 'PALESTRE' }, 
  { id: 'E571', code: '+POSPAL-08.SCL1-14_P', label: 'Posa in opera di PALESTRA LINEA', category: 'PALESTRE' }, 
  { id: 'E572', code: '+POSPENTA100', label: 'Posa in opera di TRAMPOLINO PENTAGONALE', category: 'PALESTRE' }, 
  { id: 'E573', code: '+POSPS-14PAL-08', label: 'Posa in opera di EASY GYM 2', category: 'PALESTRE' }, 
  { id: 'E574', code: '+POSPV10_P', label: 'Posa in opera di IMPIANTO DI EQUILIBRIO', category: 'PALESTRE' }, 
  { id: 'E575', code: '+POSPV21', label: 'Posa in opera di PERCORSO EQUILIBRIO', category: 'PALESTRE' }, 
  { id: 'E576', code: '+POSRETT.H', label: 'Posa in opera di TRAMPOLINO INCLUSIVE PICCOLO', category: 'PALESTRE' }, 
  { id: 'E577', code: '+POSRETT.H1', label: 'Posa in opera di TRAMPOLINO INCLUSIVE GRANDE', category: 'PALESTRE' }, 
  { id: 'E578', code: '+POSRETT100', label: 'Posa in opera di TRAMPOLINO RETTANGOLARE', category: 'PALESTRE' }, 
  { id: 'E579', code: '+POSROUND100', label: 'Posa in opera di TRAMPOLINO PICCOLO', category: 'PALESTRE' }, 
  { id: 'E580', code: '+POSROUND150', label: 'Posa in opera di TRAMPOLINO MEDIO', category: 'PALESTRE' }, 
  { id: 'E581', code: '+POSROUND200', label: 'Posa in opera di TRAMPOLINO GRANDE', category: 'PALESTRE' }, 
  { id: 'E582', code: '+POSS4-9.SCL1-9', label: 'Posa in opera di EASY GYM BABY 4', category: 'PALESTRE' }, 
  { id: 'E583', code: '+POSSG1013A3', label: 'Posa in opera di MEZZA PIRAMIDE', category: 'PALESTRE' }, 
  { id: 'E584', code: '+POSU0100.BV-4', label: 'Posa in opera di PERCORSO FANTASY', category: 'PALESTRE' }, 
  { id: 'E585', code: '+POSU0100.BV-4_P', label: 'Posa in opera di PERCORSO FANTASY 2', category: 'PALESTRE' }, 
  { id: 'E586', code: '+POSU0100.GT-06_P', label: 'Posa in opera di PERCORSO EQUILIBRIO STEP', category: 'PALESTRE' }, 
  { id: 'E587', code: '+POSU0100.PAL-01', label: 'Posa in opera di PERCORSO EQUILIBRIO', category: 'PALESTRE' }, 
  { id: 'E588', code: '+POSU0100.PAL-02_P', label: 'Posa in opera di PALESTRA PRIMITIV 1', category: 'PALESTRE' }, 
  { id: 'E589', code: '+POSU0100.PAL-05_L', label: 'Posa in opera di PARCO AVVENTURA', category: 'PALESTRE' }, 
  { id: 'E590', code: '+POSU0100.PAL-06_P', label: 'Posa in opera di PALESTRA PRIMITIV 5', category: 'PALESTRE' }, 
  { id: 'E591', code: '+POSU0100.PAL-07_P', label: 'Posa in opera di PALESTRA PRIMITIV 3', category: 'PALESTRE' }, 
  { id: 'E592', code: '+POSU0100.PAL-10_P', label: 'Posa in opera di PERCORSO FUNI', category: 'PALESTRE' }, 
  { id: 'E593', code: '+POSU0100.PAL-13_P', label: 'Posa in opera di PALESTRA PRIMITIV 4', category: 'PALESTRE' }, 
  { id: 'E594', code: '+POSU0100.PD-5', label: 'Posa in opera di PASSERELLA OSCILLANTE', category: 'PALESTRE' }, 
  { id: 'E595', code: '+POSU0100.PD-6', label: 'Posa in opera di PONTE TIBETANO', category: 'PALESTRE' }, 
  { id: 'E596', code: '+POSU0100.PD-6_P', label: 'Posa in opera di PERCORSO STEP EQUILIBRIO', category: 'PALESTRE' }, 
  { id: 'E597', code: '+POSU0100.T-9H_L', label: 'Posa in opera di PERCORSO EQUILIBRIO INCLUSIVO BABY', category: 'PALESTRE' }, 
  { id: 'E598', code: '+POSU0100.TT-17', label: 'Posa in opera di PERCORSO CON TUBO E FUNI', category: 'PALESTRE' }, 
  { id: 'E599', code: '+POSU0100_P', label: 'Posa in opera di PASSERELLA OSCILLANTE', category: 'PALESTRE' }, 
  { id: 'E600', code: '+POSU0100B.PD-6', label: 'Posa in opera di PERCORSO STEP BABY FANTASY', category: 'PALESTRE' }, 
  { id: 'E601', code: '+POSU0300', label: 'Posa in opera di TUNNEL WOOD', category: 'PALESTRE' }, 
  { id: 'E602', code: '+POSU0300.L.1', label: 'Posa in opera di TUNNEL LEONE', category: 'PALESTRE' }, 
  { id: 'E603', code: '+POSU0400.S4-9', label: 'Posa in opera di PALESTRA DENTRO FUORI', category: 'PALESTRE' }, 
  { id: 'E604', code: '+POSU0600.T.P-7', label: 'Posa in opera di LABIRINTO', category: 'PALESTRE' }, 
  { id: 'E605', code: '+POSV0800', label: 'Posa in opera di GIOCO CAMPANA', category: 'PALESTRE' }, 
  { id: 'E606', code: '+POSV0900.GT-6', label: 'Posa in opera di GIOCO PERCORSO SFERE', category: 'PALESTRE' }, 
  { id: 'E607', code: '+POCLSDR', label: 'Posa caldana drenante', category: 'PAVIMENTAZIONI' }, 
  { id: 'E608', code: '+POSCLS', label: 'Posa in opera caldana in calcestruzzo', category: 'PAVIMENTAZIONI' }, 
  { id: 'E609', code: '+POSCOL.F.001', label: 'Realizzazione fiore con numeri', category: 'PAVIMENTAZIONI' }, 
  { id: 'E610', code: '+POSCOL.F.002', label: 'Realizzazione lombrico con numeri', category: 'PAVIMENTAZIONI' }, 
  { id: 'E611', code: '+POSCOL.F.005', label: 'Realizzazione percorso sensoriale psicomotorio', category: 'PAVIMENTAZIONI' }, 
  { id: 'E612', code: '+POSCOL.F.006', label: 'Realizzazione campana classica', category: 'PAVIMENTAZIONI' }, 
  { id: 'E613', code: '+POSCOL.F.009', label: 'Realizzazione forme geometriche semplici', category: 'PAVIMENTAZIONI' }, 
  { id: 'E614', code: '+POSCOL.F.010', label: 'Realizzazione arcobaleno', category: 'PAVIMENTAZIONI' }, 
  { id: 'E615', code: '+POSCOL.F.011', label: 'Realizzazione farfalla stilizzata', category: 'PAVIMENTAZIONI' }, 
  { id: 'E616', code: '+POSCOL.F.014', label: 'Realizzazione pesce', category: 'PAVIMENTAZIONI' }, 
  { id: 'E617', code: '+POSCOL.F.015', label: 'Realizzazione fiore', category: 'PAVIMENTAZIONI' }, 
  { id: 'E618', code: '+POSCOL.F.017', label: 'Realizzazione strada', category: 'PAVIMENTAZIONI' }, 
  { id: 'E619', code: '+POSCOL.F.019', label: 'Realizzazione semaforo stilizzato', category: 'PAVIMENTAZIONI' }, 
  { id: 'E620', code: '+POSCOL.F.020', label: 'Realizzazione parcheggi con lettere e numeri', category: 'PAVIMENTAZIONI' }, 
  { id: 'E621', code: '+POSCOL.F.022', label: 'Realizzazione gioco dell\'oca stilizzato', category: 'PAVIMENTAZIONI' }, 
  { id: 'E622', code: '+POSCORT', label: 'Posa pavimentazione corteccia', category: 'PAVIMENTAZIONI' }, 
  { id: 'E623', code: '+POSGHI', label: 'Fornitura e posa pavimentazione in ghiaino', category: 'PAVIMENTAZIONI' }, 
  { id: 'E624', code: '+POSPALV', label: 'Posa pavimentazione alveolare', category: 'PAVIMENTAZIONI' }, 
  { id: 'E625', code: '+POSPAV', label: 'Posa pavimentazione smorzacadute', category: 'PAVIMENTAZIONI' }, 
  { id: 'E626', code: '+POSPAVCO', label: 'Posa pavimentazione colata', category: 'PAVIMENTAZIONI' }, 
  { id: 'E627', code: '+POSPAVSINTEITCA', label: 'Posa erbe sintetica', category: 'PAVIMENTAZIONI' }, 
  { id: 'E628', code: '+POSSAB', label: 'Fornitura e posa pavimentazione in sabbia', category: 'PAVIMENTAZIONI' }, 
  { id: 'E629', code: '+POSAE100Pb_P', label: 'Posa in opera di ALBICOCCA EASY BABY CON PALESTRA', category: 'PRIMITIV' }, 
  { id: 'E630', code: '+POSAE101A_P', label: 'Posa in opera di HOOK EASY CON ALTALENA', category: 'PRIMITIV' }, 
  { id: 'E631', code: '+POSAE102.SVPX-9_P', label: 'Posa in opera di PESCA EASY CON SCIVOLI', category: 'PRIMITIV' }, 
  { id: 'E632', code: '+POSAE103P_P', label: 'Posa in opera di MANGO EASY CON PALESTRA', category: 'PRIMITIV' }, 
  { id: 'E633', code: '+POSAF100_P', label: 'Posa in opera di FATA', category: 'PRIMITIV' }, 
  { id: 'E634', code: '+POSAF100B.SG-14_P', label: 'Posa in opera di FRAGOLA H140', category: 'PRIMITIV' }, 
  { id: 'E635', code: '+POSAF100B.SG-9_P', label: 'Posa in opera di FRAGOLA H90', category: 'PRIMITIV' }, 
  { id: 'E636', code: '+POSAF100B.T-9_P', label: 'Posa in opera di FATA BABY CON PEDANA TRIANGOLARE', category: 'PRIMITIV' }, 
  { id: 'E637', code: '+POSAF100P_P', label: 'Posa in opera di FATA CON PALESTRA', category: 'PRIMITIV' }, 
  { id: 'E638', code: '+POSAF102.PD-4.ALT-01_P', label: 'Posa in opera di MERLINO CON PASSERELLA E ALTALENA', category: 'PRIMITIV' }, 
  { id: 'E639', code: '+POSAF102.PSC1-9_P', label: 'Posa in opera di MERLINO CON PEDANA CURVA', category: 'PRIMITIV' }, 
  { id: 'E640', code: '+POSAF102.SCL1-9_P', label: 'Posa in opera di MERLINO CON PEDANA', category: 'PRIMITIV' }, 
  { id: 'E641', code: '+POSAF102B.GT-06_P', label: 'Posa in opera di MERLINO BABY CON SEDUTA', category: 'PRIMITIV' }, 
  { id: 'E642', code: '+POSAF102B.SG-6_P', label: 'Posa in opera di MERLINO BABY CON SCALA A GRADONI', category: 'PRIMITIV' }, 
  { id: 'E643', code: '+POSAF102B.TT-17_P', label: 'Posa in opera di MERLINO CON TUNNEL', category: 'PRIMITIV' }, 
  { id: 'E644', code: '+POSAF102P_P', label: 'Posa in opera di MERLINO CON PALESTRA E DUE SCIVOLI', category: 'PRIMITIV' }, 
  { id: 'E645', code: '+POSAF102SSU.PAL-05_P', label: 'Posa in opera di ANTARES CON PALESTRA SOSPESA', category: 'PRIMITIV' }, 
  { id: 'E646', code: '+POSAF104K.KK030_P', label: 'Posa in opera di ROMA CON TELEFERICA', category: 'PRIMITIV' }, 
  { id: 'E647', code: '+POSAF104K.PAL-05_P', label: 'Posa in opera di ROMA CON PALESTRA SOSPESA', category: 'PRIMITIV' }, 
  { id: 'E648', code: '+POSAF104K.TT-17_P', label: 'Posa in opera di ROMA BABY CON TUNNEL', category: 'PRIMITIV' }, 
  { id: 'E649', code: '+POSAF200_P', label: 'Posa in opera di KOS', category: 'PRIMITIV' }, 
  { id: 'E650', code: '+POSAF300H.GT-01_P', label: 'Posa in opera di SATURNO', category: 'PRIMITIV' }, 
  { id: 'E651', code: '+POSAF301H19_P', label: 'Posa in opera di SATURNO CON SCIVOLI', category: 'PRIMITIV' }, 
  { id: 'E652', code: '+POSAF703E2.PS-14_P', label: 'Posa in opera di DRAGON CON SPIRALE', category: 'PRIMITIV' }, 
  { id: 'E653', code: '+POSAF802.SWE-14_P', label: 'Posa in opera di GIULIETTA E ROMEO CON SCIVOLO A TUBO', category: 'PRIMITIV' }, 
  { id: 'E654', code: '+POSAZ150_P', label: 'Posa in opera di TORRE MINI', category: 'PRIMITIV' }, 
  { id: 'E655', code: '+POSES005.BV-7_P', label: 'Posa in opera di VILLAGGIO', category: 'PRIMITIV' }, 
  { id: 'E656', code: '+POSABACOGT-01.1', label: 'Posa in opera di PANNELLO MOLTIPLICAZIONI', category: 'SENSORIALI' }, 
  { id: 'E657', code: '+POSABACOU0400.P-7', label: 'Posa in opera di PANNELLO PINBALL', category: 'SENSORIALI' }, 
  { id: 'E658', code: '+POSAF100.TP.SG-9', label: 'Posa in opera di GIOCO SABBIA', category: 'SENSORIALI' }, 
  { id: 'E659', code: '+POSAF100.TP.SG-9_P', label: 'Posa in opera di GIOCO SABBIA PRIMITIV', category: 'SENSORIALI' }, 
  { id: 'E660', code: '+POSD0100', label: 'Posa in opera di SABBIERA VENICE PICCOLA', category: 'SENSORIALI' }, 
  { id: 'E661', code: '+POSD0200', label: 'Posa in opera di SABBIERA VENICE GRANDE', category: 'SENSORIALI' }, 
  { id: 'E662', code: '+POSD0500', label: 'Posa in opera di SABBIERA SCHOOL', category: 'SENSORIALI' }, 
  { id: 'E663', code: '+POSD0500.GT-03', label: 'Posa in opera di SABBIERA TONDA', category: 'SENSORIALI' }, 
  { id: 'E664', code: '+POSE0800', label: 'Posa in opera di GIOCO ACQUA APACHE', category: 'SENSORIALI' }, 
  { id: 'E665', code: '+POSES1100.BV-04', label: 'Posa in opera di TAVOLO MANIPOLAZIONE FIORE', category: 'SENSORIALI' }, 
  { id: 'E666', code: '+POSES1100.BV-06', label: 'Posa in opera di TAVOLO DI MANIPOLAZIONE ELICA', category: 'SENSORIALI' }, 
  { id: 'E667', code: '+POSES1100.U0600.1', label: 'Posa in opera di TAVOLO MANIPOLAZIONE BANCO DA LAVORO', category: 'SENSORIALI' }, 
  { id: 'E668', code: '+POSES1100.U0600.2', label: 'Posa in opera di TAVOLO MANIPOLAZIONE CUCINA', category: 'SENSORIALI' }, 
  { id: 'E669', code: '+POSGG2111E_P', label: 'Posa in opera di CARRUCOLA SABBIA PRIMITIV', category: 'SENSORIALI' }, 
  { id: 'E670', code: '+POSTF100', label: 'Posa in opera di SABBIERA FREE TIME', category: 'SENSORIALI' }, 
  { id: 'E671', code: '+POSU0400.C', label: 'Posa in opera di PANNELLO DENTRO FUORI', category: 'SENSORIALI' }, 
  { id: 'E672', code: '+POSU0400.P-2', label: 'Posa in opera di FOOTBALL', category: 'SENSORIALI' }, 
  { id: 'E673', code: '+POSU0400.P-7', label: 'Posa in opera di PINBALL', category: 'SENSORIALI' }, 
  { id: 'E674', code: '+POSU0400.U0600-N', label: 'Posa in opera di GIOCO DEI DADI', category: 'SENSORIALI' }, 
  { id: 'E675', code: '+POSU0600.820', label: 'Posa in opera di PANNELLO AEREO', category: 'SENSORIALI' }, 
  { id: 'E676', code: '+POSU0600.BV-2', label: 'Posa in opera di PANNELLO INGRANAGGIO', category: 'SENSORIALI' }, 
  { id: 'E677', code: '+POSU0600.BV-2.2', label: 'Posa in opera di PANNELLO BRAILLE', category: 'SENSORIALI' }, 
  { id: 'E678', code: '+POSU0600.BV-3', label: 'Posa in opera di PANNELLO GALASSIA', category: 'SENSORIALI' }, 
  { id: 'E679', code: '+POSU0600.BV-4', label: 'Posa in opera di PANNELLO ATTIVITA’', category: 'SENSORIALI' }, 
  { id: 'E680', code: '+POSU0600.BV-6', label: 'Posa in opera di PANNELLO BANCO VENDITA', category: 'SENSORIALI' }, 
  { id: 'E681', code: '+POSU0600.L.BV-4', label: 'Posa in opera di PANNELLO MUSICALE', category: 'SENSORIALI' }, 
  { id: 'E682', code: '+POSU0600.L.BV-4_P', label: 'Posa in opera di PANNELLO MUSICALE PRIMITIV', category: 'SENSORIALI' }, 
  { id: 'E683', code: '+POSU0600.O', label: 'Posa in opera di PANNELLO OPTICAL', category: 'SENSORIALI' }, 
  { id: 'E684', code: '+POSU0600.S', label: 'Posa in opera di PANNELLO SPECCHIO', category: 'SENSORIALI' }, 
  { id: 'E685', code: '+POSU0600L.BV-4.2', label: 'Posa in opera di PANNELLO TAMBURO', category: 'SENSORIALI' }, 
  { id: 'E686', code: '+POSU0600L.BV-7', label: 'Posa in opera di PANNELLO CUPOLE MUSICALI', category: 'SENSORIALI' }, 
  { id: 'E687', code: '+POSU0600-LM', label: 'Posa in opera di LEONE MUSICALE', category: 'SENSORIALI' }, 
  { id: 'E688', code: '+POSU0600-N', label: 'Posa in opera di PANNELLO NUMERI', category: 'SENSORIALI' }, 
  { id: 'E689', code: '+POSU0600-N.BV-4', label: 'Posa in opera di PANNELLI INTERATTIVI', category: 'SENSORIALI' }, 
  { id: 'E690', code: '+POSU0600-N.BV-4_C', label: 'Posa in opera di PANNELLI INTERATTIVI COLORI', category: 'SENSORIALI' }, 
  { id: 'E691', code: '+POSU0600-N.BV-4_E', label: 'Posa in opera di PANNELLI INTERATTIVI EASY', category: 'SENSORIALI' }, 
  { id: 'E692', code: '+POSU0600-N.BV-4_L', label: 'Posa in opera di PANNELLI INTERATTIVI LEAVES', category: 'SENSORIALI' }, 
  { id: 'E693', code: '+POSU0600-N.BV-4_P', label: 'Posa in opera di PANNELLI INTERATTIVI PRIMITIV', category: 'SENSORIALI' }, 
  { id: 'E694', code: '+POSU0600-N.BV-7', label: 'Posa in opera di PANNELLI MUSICALI INTERATIVI', category: 'SENSORIALI' }, 
  { id: 'E695', code: '+POSU0600-T', label: 'Posa in opera di PANNELLO TRIS', category: 'SENSORIALI' }, 
  { id: 'E696', code: '+POSU1200', label: 'Posa in opera di FIORI COMUNICANTI', category: 'SENSORIALI' }, 
  { id: 'E697', code: '+POSV0900', label: 'Posa in opera di SCACCHIERA', category: 'SENSORIALI' }, 
  { id: 'E698', code: '+POSKK030', label: 'Posa in opera di TELEFERICA', category: 'TELEFERICHE' }, 
  { id: 'E699', code: '+POSKK030.1', label: 'Posa in opera di DONDOLO VOLANTE', category: 'TELEFERICHE' }, 
  { id: 'E700', code: '+POSKK030_L', label: 'Posa in opera di TELEFERICA LEAVES', category: 'TELEFERICHE' }, 
  { id: 'E701', code: '+POSKK030_P', label: 'Posa in opera di TELEFERICA PRIMITIV', category: 'TELEFERICHE' },
  { id: 'E702', code: 'COD-0000', label: 'Manutenzioni', category: 'MANUTENZIONI' }
]

// ──────────────────────────────────────────────────────────────────────────────
// LOCALIZZAZIONE DATE
// ──────────────────────────────────────────────────────────────────────────────

/** Nomi dei giorni della settimana in italiano (0 = domenica) */
export const DAYS_IT = ['Domenica', 'Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato'] as const

/** Nomi abbreviati dei giorni (0 = domenica) */
export const DAYS_SHORT = ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'] as const

/** Nomi dei mesi in italiano (0 = gennaio) */
export const MONTHS_IT = ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno',
                           'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'] as const

/** Nomi abbreviati dei mesi (0 = gennaio) */
export const MONTHS_SHORT = ['Gen', 'Feb', 'Mar', 'Apr', 'Mag', 'Giu',
                              'Lug', 'Ago', 'Set', 'Ott', 'Nov', 'Dic'] as const
